const {chromium}=require('C:/Users/경남교육청/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('node:fs');
const assert=require('node:assert/strict');

(async()=>{
 const base=process.env.TEST_URL||'http://127.0.0.1:8787';
 const setupKey=fs.readFileSync('private/teacher-setup.txt','utf8').trim();
 const created=await fetch(base+'/api/create',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({setupKey,size:2})});
 assert.equal(created.status,201);
 const room=await created.json();
 const browser=await chromium.launch({channel:'msedge',headless:true});
 try{
  const page=await browser.newPage({viewport:{width:390,height:844}});
  const errors=[];page.on('pageerror',error=>errors.push(error.message));
  await page.goto(base+'/index.html');
  assert.equal(await page.locator('#rememberDevice').isChecked(),false,'Shared devices must not remember a student by default');
  await page.screenshot({path:'test-output/entry-v93-mobile.png'});
  const defaultContext=await browser.newContext({viewport:{width:390,height:844}});
  const defaultPage=await defaultContext.newPage();
  await defaultPage.goto(base+'/index.html');
  await defaultPage.locator('#roomCode').fill(room.roomCode);
  await defaultPage.locator('#studentCode').fill(room.students[0].code);
  await defaultPage.locator('#schoolEntry button[type=submit]').click();
  await defaultPage.waitForFunction(()=>window.classroomActive&&window.classroomData?.me);
  const sharedNext=await defaultContext.newPage();
  await sharedNext.goto(base+'/index.html');
  await sharedNext.locator('#schoolEntry').waitFor();
  assert.equal(await sharedNext.locator('#resumeStudent').count(),0,'No previous-account shortcut on a shared device');
  await defaultContext.close();
  const login=async index=>{
   await page.locator('#roomCode').fill(room.roomCode);
   await page.locator('#studentCode').fill(room.students[index].code);
   await page.locator('#rememberDevice').check();
   await page.locator('#schoolEntry button[type=submit]').click();
   await page.waitForFunction(()=>window.classroomActive&&window.classroomData?.me&&!document.querySelector('#dialog').open);
  };
  await login(0);
  await page.locator('[data-screen="activity"]').click();
  await page.locator('[data-activity="work"]').click();
  await page.locator('.school-prod [data-school-action="produce"]').click();
  await page.locator('#toast').getByText(/상추 2개를 얻었어요/).waitFor();
  assert.equal(await page.locator('#compactStudentSwitch').isVisible(),true);
  const switchBox=await page.locator('#compactStudentSwitch').boundingBox();
  assert(switchBox&&switchBox.x>=0&&switchBox.x+switchBox.width<=390,'학생 바꾸기 버튼이 휴대폰 화면 안에 있어야 합니다.');
  await page.locator('#compactStudentSwitch').click();
  await page.locator('#studentSwitchConfirm').waitFor({state:'visible'});
  assert.equal(await page.evaluate(()=>sessionStorage.getItem('village-student-token')),room.students[0].code);
  await page.locator('#studentSwitchConfirm [data-stay]').click();
  assert.equal(await page.evaluate(()=>window.classroomActive),true);
  await page.locator('#compactStudentSwitch').click();
  await Promise.all([page.waitForEvent('framenavigated'),page.locator('#studentSwitchConfirm [data-switch]').click()]);
  await page.waitForURL(url=>url.searchParams.get('entry')==='1');
  assert.equal(await page.evaluate(()=>sessionStorage.getItem('village-student-token')),null);
  assert((await page.locator('.remembered-student').innerText()).includes(room.students[0].name));
  await page.screenshot({path:'test-output/remembered-v93-mobile.png'});
  await page.locator('#resumeStudent').click();
  await page.waitForFunction(()=>window.classroomActive&&window.classroomData?.me&&!document.querySelector('#dialog').open);
  assert.equal(await page.evaluate(()=>classroomData.me.accountName),room.students[0].name);
  assert.equal(new URL(page.url()).searchParams.has('entry'),false,'The entry choice should not reappear on same-tab refresh');
  await page.reload();
  await page.waitForFunction(()=>window.classroomActive&&window.classroomData?.me);
  assert.equal(await page.evaluate(()=>classroomData.me.accountName),room.students[0].name);
  await page.locator('#compactStudentSwitch').click();
  await Promise.all([page.waitForEvent('framenavigated'),page.locator('#studentSwitchConfirm [data-switch]').click()]);
  await page.locator('#schoolEntry').waitFor();
  await login(1);
  assert.equal(await page.evaluate(()=>classroomData.me.accountName),room.students[1].name);
  const extraContext=await browser.newContext({storageState:await page.context().storageState()});
  const extra=await extraContext.newPage();
  await extra.goto(base+'/index.html');
  await extra.locator('#schoolEntry').waitFor();
  assert.equal(await extra.evaluate(()=>window.classroomActive),false,'A new tab must ask which student is using the device');
  assert.match(await extra.locator('#resumeStudent').innerText(),/학생 002 계정으로 들어가기/);
  await extra.locator('#resumeStudent').click();
  await extra.waitForFunction(()=>window.classroomActive&&window.classroomData?.me);
  assert.equal(await extra.evaluate(()=>classroomData.me.accountName),room.students[1].name);
  await extraContext.close();
  const popupPromise=page.context().waitForEvent('page');
  await page.evaluate(url=>window.open(url,'_blank'),base+'/index.html');
  const copiedTab=await popupPromise;
  await copiedTab.locator('#schoolEntry').waitFor();
  assert.equal(await copiedTab.evaluate(()=>window.classroomActive),false,'Copied sessionStorage must not log in a new tab');
  await copiedTab.close();
  await page.evaluate(()=>sessionStorage.setItem('village-pending-command',JSON.stringify({action:'plant',plot:0,requestId:crypto.randomUUID()})));
  await page.locator('#compactMenuButton').click();
  await page.locator('[data-menu-dest="logout"]').click();
  await page.locator('#studentSwitchConfirm').waitFor({state:'visible'});
  await Promise.all([page.waitForEvent('framenavigated'),page.locator('#studentSwitchConfirm [data-switch]').click()]);
  await page.waitForURL(url=>url.searchParams.get('entry')==='1');
  assert.equal(await page.evaluate(()=>sessionStorage.getItem('village-student-token')),null);
  assert.equal(await page.evaluate(()=>sessionStorage.getItem('village-pending-command')),null);
  await page.locator('#resumeStudent').click();
  await page.waitForFunction(()=>window.classroomActive&&window.classroomData?.me);
  await page.goto(base+'/campus.html');
  await page.waitForFunction(()=>typeof data!=='undefined'&&data);
  await page.locator('#compactStudentSwitch').click();
  await page.locator('#studentSwitchConfirm').waitFor({state:'visible'});
  await page.locator('#studentSwitchConfirm [data-stay]').click();
  assert.equal(await page.evaluate(()=>!!token),true);
  await page.locator('#compactStudentSwitch').click();
  await Promise.all([page.waitForEvent('framenavigated'),page.locator('#studentSwitchConfirm [data-switch]').click()]);
  await page.locator('#resumeStudent').waitFor();
  assert.deepEqual(errors,[]);
  console.log('PASS: visible account switch and menu logout preserve both student accounts');
 }finally{await browser.close()}
})().catch(error=>{console.error(error);process.exit(1)});
