const fs=require('fs'),assert=require('assert/strict'),crypto=require('crypto'),{createRequire}=require('module');const {chromium}=createRequire('C:/Users/경남교육청/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/package.json')('playwright');
const base='http://127.0.0.1:8800';
(async()=>{fs.mkdirSync('test-output/action-save',{recursive:true});const results=[],browser=await chromium.launch({channel:'msedge',headless:true});async function api(route,b,t){const r=await fetch(base+route,{method:b?'POST':'GET',headers:{'content-type':'application/json',...(t?{authorization:'Bearer '+t}:{})},...(b?{body:JSON.stringify(b)}:{})});assert(r.ok);return r.json()}
try{for(const mode of ['trial','classroom']){const token=mode==='trial'?(await api('/api/trial',{key:crypto.randomBytes(16).toString('hex')})).token:(await api('/api/create',{size:2,setupKey:fs.readFileSync('private/teacher-setup.txt','utf8').trim()})).students[0].code;
for(const width of [1360,390]){const c=await browser.newContext({viewport:{width,height:900}});await c.addInitScript(t=>{sessionStorage.setItem('village-student-token',t);const raf=requestAnimationFrame;window.requestAnimationFrame=cb=>raf(function deliver(ts){if(window.__freezeAnimation)raf(deliver);else cb(ts)})},token);const p=await c.newPage();await p.goto(base+'/#farm');await p.waitForFunction(()=>window.farm3DReady&&window.classroomActive);async function check(name,f){try{await f();results.push({mode,width,name,pass:true})}catch(e){results.push({mode,width,name,pass:false,error:e.message})}}
await check('plant saved before animation and library navigation',async()=>{await p.locator('[data-bed3d="'+(width===390?1:0)+'"]').click();await p.evaluate(()=>window.__freezeAnimation=true);await p.locator('.selected-bed-action').click();await p.locator('.compact-tabs [data-screen=study]').click();await p.waitForURL('**/campus.html#study');await p.waitForFunction(()=>typeof data!=='undefined'&&!!data);const d=await api('/api/state',null,token);assert.equal(d.me.state.farm.plots[width===390?1:0].seeded,true);await p.locator('.compact-tabs [data-screen=farm]').click();await p.waitForFunction(()=>window.farm3DReady&&window.classroomActive);assert.equal(await p.locator('[data-bed3d="'+(width===390?1:0)+'"]').getAttribute('aria-label'),(width===390?'2':'1')+'번 밭 물 주기')});
await p.goto(base+'/#village');await p.waitForFunction(()=>window.farm3DReady&&window.classroomActive);await check('market has one entry flow',async()=>assert.equal(await p.locator('[data-village-section=market]:visible').count(),0));
if(mode==='trial')await check('trial plaza works without presence server',async()=>{await p.route('**/api/plaza',r=>r.abort());await p.reload();await p.waitForFunction(()=>window.farm3DReady&&window.classroomActive);await p.waitForFunction(()=>document.querySelector('.plaza-connection')?.textContent.includes('혼자 체험'),null,{timeout:5000});await p.locator('[data-plaza-market]').click();await p.waitForURL('**/#market',{timeout:12000})});
await p.screenshot({path:`test-output/action-save/${mode}-${width}.png`,fullPage:true});await c.close();}}
}finally{await browser.close();fs.writeFileSync('test-output/action-save/'+(process.env.PHASE||'report')+'.json',JSON.stringify(results,null,2));console.log(JSON.stringify(results));process.exitCode=results.some(r=>!r.pass)?1:0}})().catch(e=>{console.error(e);process.exitCode=1});
