import assert from 'node:assert/strict';import {readFile,mkdir,writeFile} from 'node:fs/promises';import {performance} from 'node:perf_hooks';import {DatabaseSync} from 'node:sqlite';import path from 'node:path';import {fileURLToPath} from 'node:url';
const root=new URL('../',import.meta.url),base=process.env.TEST_URL||'http://127.0.0.1:8787',key=(await readFile(new URL('private/teacher-setup.txt',root),'utf8')).trim(),times=[];
const dbPath=path.resolve(process.env.TEST_DB||'');const testRoot=path.resolve(fileURLToPath(root),'test-output');assert(process.env.TEST_DB&&dbPath.startsWith(testRoot+path.sep),'Set TEST_DB to an isolated file under test-output before running the API load test');assert(new URL(base).hostname==='127.0.0.1','The API load test must target an isolated local server');
async function req(route,b,token=''){const t=performance.now(),r=await fetch(base+route,{method:b?'POST':'GET',headers:{'content-type':'application/json',...(process.env.SITES_AUTH?{'OAI-Sites-Authorization':'Bearer '+process.env.SITES_AUTH}:{}),...(token?{authorization:'Bearer '+token}:{})},...(b?{body:JSON.stringify(b)}:{})});const d=await r.json();return {status:r.status,data:d,ms:performance.now()-t}}
let seq=0;const act=(token,action,extra={},id)=>req('/api/action',{action,...extra,requestId:id||'qa-command-'+(++seq)},token);
const health=await req('/api/health');assert.equal(health.status,200,JSON.stringify(health));const made=await req('/api/create',{setupKey:key,size:120});assert.equal(made.status,201,JSON.stringify(made));const room=made.data;
const joins=await Promise.all(room.students.map(s=>req('/api/join',{roomCode:room.roomCode,code:s.code})));assert(joins.every(x=>x.status===200));times.push({test:'120 concurrent joins',...stats(joins)});
const snapshots=await Promise.all(room.students.map(s=>req('/api/state',null,s.code)));assert(snapshots.every(x=>x.status===200));times.push({test:'120 concurrent snapshots',...stats(snapshots)});
const productions=await Promise.all(room.students.map(s=>act(s.code,'produce')));assert(productions.every(x=>x.status===200),JSON.stringify(productions.filter(x=>x.status!==200)));times.push({test:'120 concurrent production writes',...stats(productions)});
let teacher=await req('/api/state',null,room.teacherKey);const totalBefore=teacher.data.players.reduce((sum,p)=>sum+p.stock.reduce((a,b)=>a+b,0),0);assert.equal(totalBefore,240);
const student0=room.students[0].code;const replay=await Promise.all(Array.from({length:12},()=>act(student0,'produce',{},'same-request-0001')));assert(replay.every(x=>x.status===200));let check=await req('/api/state',null,student0);assert.equal(check.data.me.state.stock[0],4,'duplicate production granted');
const wrongRole=await req('/api/teacher',{day:1,weather:0,phase:'개인 성장',market:true,paused:false},student0);assert.equal(wrongRole.status,403);
const settings={day:1,weather:0,phase:'개인 성장',market:true,paused:false};assert.equal((await req('/api/teacher',settings,room.teacherKey)).status,200);
const offer=await act(student0,'offer',{giveItem:0,giveQty:1,wantItem:1,wantQty:1});assert.equal(offer.status,200);const offerId=offer.data.offers.find(o=>o.seller===offer.data.me.id).id;
// New classrooms start every student as a farmer. Prepare milk only in an
// isolated test database so the 30-buyer race tests trading, not cow unlocks.
const buyers=room.students.slice(1,31);const fixture=new DatabaseSync(dbPath);fixture.exec('BEGIN IMMEDIATE');try{for(const p of teacher.data.players.slice(1,31))fixture.prepare("UPDATE players SET state=json_set(state,'$.stock[1]',1) WHERE id=?").run(p.id);fixture.exec('COMMIT')}catch(error){fixture.exec('ROLLBACK');throw error}finally{fixture.close()}
const race=await Promise.all(buyers.map(s=>act(s.code,'accept',{offer:offerId})));assert.equal(race.filter(x=>x.status===200).length,1,'exactly one buyer must accept the offer');assert(race.every(x=>[200,409].includes(x.status)),JSON.stringify(race.filter(x=>![200,409].includes(x.status))));times.push({test:'30 buyers race for one offer',...stats(race)});
teacher=await req('/api/state',null,room.teacherKey);assert.equal(teacher.data.players.reduce((sum,p)=>sum+p.stock.reduce((a,b)=>a+b,0),0),totalBefore+2+buyers.length,'exchange did not conserve stock');
const fake=await act(student0,'sell',{item:0,qty:999});assert.equal(fake.status,400);const bad=await req('/api/action',{action:'produce',requestId:'malicious-command',state:{coins:999999}},student0);assert.equal(bad.status,200);check=await req('/api/state',null,student0);assert.equal(check.data.me.state.coins,80);
assert.equal((await req('/api/teacher',{...settings,paused:true},room.teacherKey)).status,200);assert.equal((await act(student0,'plant',{plot:0})).status,423);await req('/api/teacher',settings,room.teacherKey);
assert.equal((await act(student0,'plant',{plot:0})).status,200);assert.equal((await act(student0,'water',{plot:0})).status,200);assert.equal((await act(student0,'harvest',{plot:0})).status,409);
const other=await req('/api/create',{setupKey:key,size:1});const cross=await act(other.data.students[0].code,'accept',{offer:offerId});assert.equal(cross.status,409);
await req('/api/teacher',{...settings,phase:'협력'},room.teacherKey);assert.equal((await act(student0,'donate',{item:0,qty:1})).status,200);teacher=await req('/api/state',null,room.teacherKey);assert.equal(teacher.data.room.coop[0],1);
const invalidToken=await req('/api/state',null,'0'.repeat(48));assert.equal(invalidToken.status,401);
await mkdir(new URL('test-output/',root),{recursive:true});await writeFile(new URL('test-output/api-report.json',root),JSON.stringify({testedAt:new Date().toISOString(),environment:'Isolated local Node 22 + SQLite WAL; HTTP load from one machine, not 120 physical browsers',passed:['120 joins','120 reads','120 writes','idempotency replay','single-winner trade race','inventory conservation','negative-stock prevention','server authority','teacher authorization','pause enforcement','early-harvest rejection','cross-class isolation','cooperation accounting','invalid token rejection'],metrics:times},null,2));await writeFile(new URL('private/qa-session.json',root),JSON.stringify(room));console.log(JSON.stringify({passed:true,metrics:times}));
function stats(rows){const sorted=rows.map(x=>x.ms).sort((a,b)=>a-b);return {requests:rows.length,p50_ms:Math.round(sorted[Math.floor(sorted.length*.5)]),p95_ms:Math.round(sorted[Math.min(sorted.length-1,Math.floor(sorted.length*.95))]),max_ms:Math.round(sorted.at(-1))}}

