import assert from 'node:assert/strict';import {DatabaseSync} from 'node:sqlite';import {api} from '../src/api.mjs';import {writeFile} from 'node:fs/promises';
const sql=new DatabaseSync(':memory:');sql.exec('PRAGMA foreign_keys=ON');function prepare(sqlText,args=[]){return {bind(...v){return prepare(sqlText,v)},async first(){return sql.prepare(sqlText).get(...args)||null},async all(){return {results:sql.prepare(sqlText).all(...args)}},async run(){const r=sql.prepare(sqlText).run(...args);return {meta:{changes:Number(r.changes)}}},sqlText,args}}const db={prepare,async batch(stmts){sql.exec('BEGIN');try{const out=[];for(const s of stmts)out.push(await s.run());sql.exec('COMMIT');return out}catch(e){sql.exec('ROLLBACK');throw e}}};let clock=Date.now();const realNow=Date.now;Date.now=()=>clock;
async function req(path,body,token){const r=await api(new Request('http://test'+path,{method:body?'POST':'GET',headers:{'content-type':'application/json',...(token?{authorization:'Bearer '+token}:{})},...(body?{body:JSON.stringify(body)}:{})}),{DB:db,TEACHER_SETUP_KEY:'test-key'});return {status:r.status,data:await r.json()}}const ok=r=>{assert.equal(r.status,200,JSON.stringify(r));return r.data};
try{const rooms=[];for(let i=0;i<5;i++){const r=await req('/api/create',{setupKey:'test-key',size:2});assert.equal(r.status,201);rooms.push(r.data)}const t=rooms[0].teacherKey,student=rooms[0].students[0].code,friend=rooms[1].students[0].code;
assert.equal((await req('/api/campus/link',{code:rooms[1].roomCode,teacherKey:rooms[1].teacherKey},student)).status,403);assert.equal((await req('/api/campus/link',{code:rooms[1].roomCode,teacherKey:'invalid'},t)).status,403);for(let i=1;i<4;i++)ok(await req('/api/campus/link',{code:rooms[i].roomCode,teacherKey:rooms[i].teacherKey,label:(i+1)+'반',homeLabel:'1반'},t));assert.equal((await req('/api/campus/link',{code:rooms[4].roomCode,teacherKey:rooms[4].teacherKey,label:'5반'},t)).status,409);
let board=ok(await req('/api/campus',null,student));assert.equal(board.rooms.length,4);const otherId=board.rooms.find(r=>r.code===rooms[1].roomCode).id;assert.equal(ok(await req('/api/state?classroom='+otherId,null,t)).room.id,otherId);assert.equal((await req('/api/state?classroom='+otherId,null,student)).status,403);const outsider=ok(await req('/api/state',null,rooms[4].teacherKey)).room.id;assert.equal((await req('/api/state?classroom='+outsider,null,t)).status,403);
assert.equal((await req('/api/campus/visit',{destination:otherId},student)).status,423);ok(await req('/api/campus/settings',{travel:true,library:true,label:'1반'},t));assert.equal((await req('/api/campus/visit',{destination:otherId},student)).status,403);assert.equal((await req('/api/campus/passport',{answer:0},student)).status,400);ok(await req('/api/campus/passport',{answer:1},student));assert.equal(ok(await req('/api/campus/visit',{destination:otherId},student)).residents.length,2);assert.equal((await req('/api/campus/visit',{destination:outsider},student)).status,403);
const study=(action,extra={},who=student)=>req('/api/campus/study',{action,id:'study-unit-001',...extra},who);board=ok(await study('start',{goal:'비공개 목표',plan:15,seat:'창가'}));assert.equal(board.current.elapsed,0);assert.equal(ok(await study('start',{goal:'비공개 목표',plan:15,seat:'창가'})).current.id,'study-unit-001');assert.equal((await study('start',{id:'study-unit-002',goal:'다른 창',plan:15,seat:'창가'})).status,409);
const peers=ok(await req('/api/campus',null,friend));assert.equal(peers.peers.length,1);assert(!JSON.stringify(peers).includes('비공개 목표'));assert.equal((await study('finish',{minutes:40,reflection:'시간 조작'})).status,400);assert.equal((await study('pause',{},friend)).status,404);
for(let i=0;i<4;i++){clock+=15000;board=ok(await study('heartbeat'))}assert.equal(board.current.elapsed,60);ok(await study('pause'));clock+=60000;board=ok(await study('heartbeat'));assert.equal(board.current.elapsed,60);ok(await study('resume'));clock+=46000;board=ok(await study('heartbeat'));assert.equal(board.current.status,'paused');assert.equal(board.current.elapsed,60);
board=ok(await study('finish',{minutes:1,reflection:'개념을 한 가지 정리했어요'}));assert.equal(board.points,6);assert.equal(board.current,null);assert.equal(ok(await study('finish',{minutes:1,reflection:'중복'})).points,6);const teacher=ok(await req('/api/campus',null,t));assert(teacher.records.some(r=>r.reflection==='개념을 한 가지 정리했어요'));assert.equal(ok(await req('/api/campus?classroom='+otherId,null,t)).records.length,0);
for(let j=2;j<=6;j++){const id='study-unit-00'+j;ok(await study('start',{id,goal:'다음 목표',plan:15,seat:'도서관'}));for(let k=0;k<4;k++){clock+=15000;ok(await study('heartbeat',{id}))}board=ok(await study('finish',{id,minutes:1,reflection:'완료 기록'}))}assert.equal(board.points,30,'daily cap');
ok(await req('/api/campus/settings',{travel:false,library:false,label:'1반'},t));assert.equal((await study('start',{id:'study-unit-007',goal:'닫힌 학교',plan:15,seat:'창가'})).status,423);assert.equal((await req('/api/campus/visit',{destination:otherId},student)).status,423);
await writeFile('test-output/campus-unit-report.json',JSON.stringify({passed:true,checks:['four-class limit and ownership','managed class isolation','passport and travel gate','student goal privacy across classes','one active session','server clock only','pause and disconnect stop time','other actor denied','finish idempotency','daily 30P cap','teacher records scoped','library closure']},null,2));console.log('PASS: 12 campus authorization, privacy, timer and reward invariants');}finally{Date.now=realNow;sql.close()}
