const fs=require('fs'),assert=require('assert/strict'),crypto=require('crypto'),{createRequire}=require('module');
const {chromium}=createRequire('C:/Users/경남교육청/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/package.json')('playwright');
const base=process.env.TEST_URL||'http://127.0.0.1:8801',phase=process.env.PHASE||'after';
(async()=>{const browser=await chromium.launch({channel:'msedge',headless:true}),results=[];fs.mkdirSync('test-output/farm-hud',{recursive:true});async function api(path,body){const r=await fetch(base+path,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});assert(r.ok);return r.json()}
try{for(const [mode,width,height] of [['trial',1366,768],['classroom',1366,768],['classroom',1024,768],['trial',390,844]]){const token=mode==='trial'?(await api('/api/trial',{key:crypto.randomBytes(16).toString('hex')})).token:(await api('/api/create',{size:1,setupKey:fs.readFileSync('private/teacher-setup.txt','utf8').trim()})).students[0].code;const c=await browser.newContext({viewport:{width,height},hasTouch:width<1100});await c.addInitScript(t=>sessionStorage.setItem('village-student-token',t),token);const p=await c.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(base+'/#farm');await p.waitForFunction(()=>window.farm3DReady&&window.classroomActive);await p.waitForTimeout(500);
async function check(name,fn){try{await fn();results.push({mode,width,name,pass:true})}catch(e){results.push({mode,width,name,pass:false,error:e.message})}}
await p.locator('[data-bed3d="0"]').click();
await check('map contains HUD and selected plot action',async()=>{assert(await p.locator('.farm3d-viewport .selected-bed-action').isVisible());assert(await p.locator('.farm-hud').isVisible());assert.equal(await p.locator('.bed-status-icon').count(),6)});
async function geometry(){const boxes=await p.evaluate(()=>{const b=s=>{const r=document.querySelector(s).getBoundingClientRect();return {x:r.x,y:r.y,right:r.right,bottom:r.bottom}};return {map:b('.farm3d-viewport'),action:b('.selected-bed-info'),scroll:scrollY}});assert.equal(boxes.scroll,0);assert(boxes.action.bottom-boxes.action.y<=175,'Callout must remain compact');assert(boxes.map.bottom<=height&&boxes.map.y>=0);assert(boxes.action.x>=boxes.map.x&&boxes.action.right<=boxes.map.right&&boxes.action.y>=boxes.map.y&&boxes.action.bottom<=boxes.map.bottom)}
await check('no scroll and action remains inside map',geometry);
if(phase!=='before'){
await p.locator('.selected-bed-action').click();await p.waitForFunction(()=>state.farm.plots[0].seeded&&!window.classroomSaving);await p.waitForFunction(()=>!document.querySelector('.selected-bed-action').disabled);await check('water needed icon',async()=>assert.equal(await p.locator('[data-bed3d="0"] .bed-status-icon').textContent(),'💧'));await p.locator('.selected-bed-action').click();await p.waitForFunction(()=>state.farm.plots[0].wateredAt>0);await check('growth countdown stays on map',async()=>{assert.match(await p.locator('.selected-bed-info').textContent(),/새싹|성장/);await geometry()});await p.waitForFunction(()=>document.querySelector('.selected-bed-action').textContent==='수확하기'&&!document.querySelector('.selected-bed-action').disabled,null,{timeout:30000});await p.locator('.selected-bed-action').click();await p.waitForFunction(()=>state.farm.picked===2);
await check('harvest HUD and notice without scrolling',async()=>{assert.match(await p.locator('.farm-hud').textContent(),/보관.*2/);assert.doesNotMatch(await p.locator('.selected-bed-info').innerText(),/작업 중/,'Saved harvest must not still appear unfinished');assert(await p.locator('.farm3d-viewport .first-harvest-notice').isVisible());await geometry()});await p.locator('.first-harvest-notice button').click();await p.screenshot({path:`test-output/farm-hud/${mode}-${width}.png`});
await p.locator('.compact-tabs [data-screen=village]').click();await check('farm overlays absent in village',async()=>assert.equal(await p.locator('.farm-hud:visible,.selected-bed-info:visible').count(),0));await p.locator('.compact-tabs [data-screen=farm]').click();await p.reload();await p.waitForFunction(()=>window.farm3DReady&&window.classroomActive);await check('harvest persists and no JS error or overflow',async()=>{assert.equal(await p.evaluate(()=>state.farm.picked),2);assert.equal(errors.length,0,errors.join(';'));assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth))});
}await c.close();}}finally{await browser.close();fs.writeFileSync(`test-output/farm-hud/${phase}.json`,JSON.stringify(results,null,2));console.log(JSON.stringify(results));process.exitCode=results.some(r=>!r.pass)?1:0}})().catch(e=>{console.error(e);process.exitCode=1});
