import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {createRequire} from 'node:module';
import path from 'node:path';

const base=process.env.TEST_URL||'http://127.0.0.1:8787';
assert(new URL(base).hostname==='127.0.0.1'&&process.env.TEST_DB&&path.resolve(process.env.TEST_DB).startsWith(path.resolve('test-output')+path.sep),'Use an isolated local test database');
const require=createRequire(import.meta.url);
const {chromium}=require('C:/Users/경남교육청/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const setup=(await readFile('private/teacher-setup.txt','utf8')).trim();
async function api(route,body,token){const response=await fetch(base+route,{method:body?'POST':'GET',headers:{'content-type':'application/json',...(token?{authorization:'Bearer '+token}:{})},...(body?{body:JSON.stringify(body)}:{})});const data=await response.json();assert(response.ok,route+': '+JSON.stringify(data));return data}

const room=await api('/api/create',{setupKey:setup,size:3});
const [seller,recipient,observer]=room.students.map(student=>student.code);
await api('/api/teacher',{day:1,weather:1,phase:'협력',market:true,paused:false},room.teacherKey);
await api('/api/action',{action:'produce',requestId:'gift-ui-produce'},seller);
const browser=await chromium.launch({channel:'msedge',headless:true});
const errors=[];
try{
 const contexts=await Promise.all([seller,recipient,observer].map((token,index)=>browser.newContext({viewport:{width:index===1?390:768,height:844}})));
 for(let i=0;i<contexts.length;i++)await contexts[i].addInitScript(token=>sessionStorage.setItem('village-student-token',token),[seller,recipient,observer][i]);
 const pages=await Promise.all(contexts.map(context=>context.newPage()));
 for(const page of pages)page.on('pageerror',error=>errors.push(error.message));
 await Promise.all(pages.map(page=>page.goto(base+'/#market')));
 const [sellerPage,recipientPage,observerPage]=pages;
 await Promise.all(pages.map(page=>page.locator('#marketSquare').waitFor()));
 await recipientPage.waitForFunction(()=>document.querySelector('.market-count')?.textContent.includes('3명'),null,{timeout:25000});
 assert.equal(await recipientPage.locator('.market-visitor:not(.market-practice-visitor)').count(),2,'Both classmates must appear locally beside the recipient');
 assert.equal(await recipientPage.locator('#marketHero').count(),1,'The recipient avatar must also appear');
 await recipientPage.waitForFunction(()=>document.querySelector('.market-plaza.market-3d')?.dataset.actors==='3');
 const nameplates=await recipientPage.locator('.market-visitor:not(.market-practice-visitor),#marketHero').evaluateAll(nodes=>nodes.map(node=>{const r=node.getBoundingClientRect();return {left:r.left,right:r.right,top:r.top,bottom:r.bottom}}));
 for(let i=0;i<nameplates.length;i++)for(let j=i+1;j<nameplates.length;j++){const a=nameplates[i],b=nameplates[j];assert(a.right<=b.left||b.right<=a.left||a.bottom<=b.top||b.bottom<=a.top,'Three student nameplates must not overlap on a narrow screen')}
 assert.match(await recipientPage.locator('.market-stall').last().innerText(),/학생 002의 가판대/,'Own stand needs a visible label');
 const standOrder=await recipientPage.locator('.market-stall[data-market-peer]').evaluateAll(nodes=>nodes.map(node=>node.dataset.marketPeer));
 await recipientPage.reload();
 await recipientPage.waitForFunction(()=>document.querySelector('.market-count')?.textContent.includes('3명'),null,{timeout:25000});
 assert.deepEqual(await recipientPage.locator('.market-stall[data-market-peer]').evaluateAll(nodes=>nodes.map(node=>node.dataset.marketPeer)),standOrder,'Refreshing must not swap stand positions');
 const sellerId=await sellerPage.evaluate(()=>classroomData.me.id),recipientId=await recipientPage.evaluate(()=>classroomData.me.id);
 await recipientPage.locator(`.market-visitor[data-market-peer="${sellerId}"]`).click();
 assert.match(await recipientPage.locator('.market-detail').innerText(),/에게 인사하기/);
 assert.equal(await recipientPage.locator('.market-detail [data-market-greet]').count(),3);
 let actorMoved=false;for(let attempt=0;attempt<24;attempt++){const presence=await api('/api/market-presence',null,recipient),self=presence.visitors.find(row=>row.id===recipientId),friend=presence.visitors.find(row=>row.id===sellerId);const col=friend.spot%6,adjacent=[col<5?friend.spot+1:friend.spot-1,col>0?friend.spot-1:friend.spot+1,(friend.spot+6)%12];if(adjacent.includes(self.spot)){actorMoved=true;break}await recipientPage.waitForTimeout(250)}
 assert(actorMoved,'Clicking a friend character must move beside that friend');
 const cardBottom=await recipientPage.locator('.market-detail').evaluate(node=>node.getBoundingClientRect().bottom);
 assert(cardBottom<=844,`390px friend card should fit without scrolling, bottom=${cardBottom}`);
 await recipientPage.screenshot({path:'test-output/market-v87-mobile.png'});
 await sellerPage.locator(`.market-visitor[data-market-peer="${recipientId}"]`).click();
 const wideCardBottom=await sellerPage.locator('.market-detail').evaluate(node=>node.getBoundingClientRect().bottom);assert(wideCardBottom<=844,`768px friend card should fit without scrolling, bottom=${wideCardBottom}`);
 await sellerPage.locator('.market-detail [data-market-greet="wave"]').click();
 await sellerPage.locator('#marketHero .market-greeting').waitFor({timeout:10000});
 await sellerPage.locator('#marketHero .market-greeting').waitFor({state:'detached',timeout:4000});
 await recipientPage.waitForFunction(id=>!!document.querySelector(`.market-visitor[data-market-peer="${id}"] .market-greeting`),sellerId,{timeout:10000});
 assert.equal(await observerPage.locator(`.market-visitor[data-market-peer="${sellerId}"] .market-greeting`).count(),0,'Greeting should appear only to the selected friend');
 assert.match(await recipientPage.locator(`.market-visitor[data-market-peer="${sellerId}"] .market-greeting`).evaluate(node=>getComputedStyle(node).animationName),/marketGreeting/);
 const firstGreeted=await recipientPage.locator(`.market-visitor[data-market-peer="${sellerId}"] .market-greeting`).getAttribute('data-greeted');
 await recipientPage.waitForTimeout(5300);
 const nameBefore=await recipientPage.locator(`.market-visitor[data-market-peer="${sellerId}"] .visitor-name`).boundingBox();
 await sellerPage.locator('.market-detail [data-market-greet="wave"]').click();
 await recipientPage.waitForFunction(({id,first})=>document.querySelector(`.market-visitor[data-market-peer="${id}"] .market-greeting`)?.dataset.greeted!==first,{id:sellerId,first:firstGreeted},{timeout:10000});
 const nameAfter=await recipientPage.locator(`.market-visitor[data-market-peer="${sellerId}"] .visitor-name`).boundingBox();
 assert(Math.abs(nameBefore.y-nameAfter.y)<2,'Greeting must not push the nameplate upward');
 const observerId=await observerPage.evaluate(()=>classroomData.me.id);
 await observerPage.evaluate(()=>{window.__testHidden=true;Object.defineProperty(document,'hidden',{configurable:true,get:()=>window.__testHidden});document.dispatchEvent(new Event('visibilitychange'))});
 await sellerPage.waitForFunction(id=>!!document.querySelector(`.market-visitor.away[data-market-peer="${id}"]`),observerId,{timeout:12000});
 assert(Number(await sellerPage.locator(`.market-visitor.away[data-market-peer="${observerId}"]`).evaluate(node=>getComputedStyle(node).opacity))<.7,'Away classmate must fade');
 await observerPage.evaluate(()=>{window.__testHidden=false;document.dispatchEvent(new Event('visibilitychange'))});
 await observerPage.waitForFunction(()=>document.querySelector('.market-count')?.textContent.includes('3명'),null,{timeout:6000});
 await recipientPage.locator('#newSchoolOffer').click();
 assert.match(await recipientPage.locator('#dialog').innerText(),/내 농장에서 상추를 수확한 뒤 다시 와 주세요/);
 assert.equal(await recipientPage.locator('#postSchoolOffer').isEnabled(),false);
 assert.equal(await recipientPage.locator('#marketGoFarm').isVisible(),true);
 await recipientPage.locator('#dialog [data-close]').click();
 await sellerPage.locator('#compactPrices').click();
 assert.match(await sellerPage.locator('#compactPriceBox').innerText(),/오늘 두 값이 같을 수도 있어요/);
 assert.match(await sellerPage.locator('#compactPriceBox').innerText(),/마을 매입가를 참고/);
 await sellerPage.keyboard.press('Escape');
 await sellerPage.locator('#newSchoolOffer').click();
 await sellerPage.locator('#schoolGift').check();
 assert.equal(await sellerPage.locator('[data-market-want]').first().isVisible(),false);
 await sellerPage.locator('#postSchoolOffer').click();
 await sellerPage.waitForFunction(()=>!document.querySelector('#dialog').open);
 await sellerPage.locator('[data-market-mine]').click();
 await sellerPage.locator('[data-market-trade]').first().click();
 assert.match(await sellerPage.locator('#dialog').innerText(),/돌려받을 물건:.*상추 1개/);
 assert.equal((await sellerPage.locator('#dialog').innerText()).match(/학생 001/g)?.length||0,0,'Cancel dialog should not show the same person on both sides');
 await sellerPage.locator('#dialog [data-close]').click();
 await recipientPage.waitForFunction(id=>document.querySelector(`.market-stall[data-market-peer="${id}"] .stall-goods`)?.textContent.includes('🎁'),sellerId,{timeout:12000});
 await recipientPage.locator(`.market-stall[data-market-peer="${sellerId}"]`).click();
 await recipientPage.locator('[data-market-trade]').first().click();
 assert.match(await recipientPage.locator('#dialog').innerText(),/내가 내는 물건은 없어요/);
 assert.equal(await recipientPage.locator('#confirmSchoolTrade').isEnabled(),true);
 await recipientPage.locator('#confirmSchoolTrade').click();
 await recipientPage.waitForFunction(()=>!document.querySelector('#dialog').open);
 const [sellerState,recipientState]=await Promise.all([api('/api/state',null,seller),api('/api/state',null,recipient)]);
 assert.equal(sellerState.me.state.stock[0],1);
 assert.equal(recipientState.me.state.stock[0],1);
 assert.deepEqual(errors,[]);
 console.log('PASS: 390px zero-stock path, three visible avatars, gift offer and claim, and price guidance');
}finally{await browser.close()}
