const {chromium}=require('C:/Users/경남교육청/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('node:fs');
const assert=require('node:assert/strict');

(async()=>{
 const base=process.env.TEST_URL||'http://127.0.0.1:8793';
 assert.equal(new URL(base).hostname,'127.0.0.1');
 const setupKey=fs.readFileSync('private/teacher-setup.txt','utf8').trim();
 const post=async(route,body,token='')=>{const response=await fetch(base+route,{method:'POST',headers:{'content-type':'application/json',...(token?{authorization:'Bearer '+token}:{})},body:JSON.stringify(body)});const data=await response.json();assert(response.ok,`${route}: ${JSON.stringify(data)}`);return data};
 const room=await post('/api/create',{setupKey,size:2});
 await post('/api/teacher',{day:1,weather:0,phase:'개인 성장',market:false,paused:true},room.teacherKey);
 const browser=await chromium.launch({headless:true,channel:'msedge'});
 try{
  const page=await browser.newPage({viewport:{width:1366,height:768}}),errors=[];
  page.on('pageerror',error=>errors.push(error.message));
  let plazaPosts=0,marketPosts=0;
  page.on('request',request=>{if(request.method()!=='POST')return;const url=new URL(request.url());if(url.pathname==='/api/plaza')plazaPosts++;if(url.pathname==='/api/market-presence')marketPosts++});
  await page.goto(base,{waitUntil:'domcontentloaded'});
  await page.locator('#roomCode').fill(room.roomCode);
  await page.locator('#studentCode').fill(room.students[0].code);
  await page.locator('#schoolEntry button[type=submit]').click();
  await page.waitForFunction(()=>window.classroomActive&&classroomData.room.paused);
  assert.equal(await page.locator('.class-pause-banner').isVisible(),true);
  assert.equal(await page.locator('#farmAlert .storm-repair-guide').count(),0,'sunny paused farm must not claim a flood');
  assert.equal(await page.locator('#compactStudentSwitch').count(),0);
  const farmHeader=await page.locator('header').boundingBox();
  await page.locator('#compactPrices').click();
  assert.match(await page.locator('[data-price-note]').textContent(),/당근·토마토·감자·딸기/);
  await page.locator('#compactPrices').click();
  await page.screenshot({path:'test-output/pause-farm.png'});
  await page.locator('#compactMenuButton').click();
  assert.equal(await page.locator('[data-menu-dest=logout]').isVisible(),true);
  await page.locator('#closeCompactMenu').click();
  await page.locator('[data-screen=village]').click();
  await page.waitForTimeout(11000);
  assert.equal(await page.locator('.class-pause-banner').isVisible(),true);
  assert.match(await page.locator('.plaza-connection').textContent(),/선생님이 수업을 잠시 멈추었어요/);
  assert(plazaPosts<=1,`paused plaza posted ${plazaPosts} times`);
  await page.evaluate(()=>window.villageNavigate('market'));
  await page.waitForTimeout(11000);
  assert.match(await page.locator('.market-count').textContent(),/선생님이 수업을 잠시 멈추었어요/);
  assert(marketPosts<=1,`paused market posted ${marketPosts} times`);
  await page.locator('[data-screen=activity]').click();
  assert.equal(await page.locator('.class-pause-banner').isVisible(),true);
  await page.locator('#startCompactQuiz').click();
  assert.match(await page.locator('#studentNavigationStatus').textContent(),/선생님이 수업을 잠시 멈추었어요/);
  await page.locator('[data-screen=passport]').click();
  assert.equal(await page.locator('.class-pause-banner').isVisible(),true);
  await page.locator('[data-screen=study]').click();
  await page.waitForURL(/campus\.html/);
  await page.waitForFunction(()=>document.querySelector('.class-pause-banner')?.hidden===false);
  assert.equal(await page.locator('.class-pause-banner').isVisible(),true);
  assert.equal(await page.locator('#compactStudentSwitch').count(),0);
  await page.evaluate(()=>scrollTo(0,0));
  const libraryHeader=await page.locator('header').boundingBox();
  assert.equal(libraryHeader.x,farmHeader.x);
  assert.equal(libraryHeader.width,farmHeader.width);
  await page.screenshot({path:'test-output/pause-library.png'});
  await page.setViewportSize({width:390,height:844});
  const banner=await page.locator('.class-pause-banner').boundingBox();
  assert(banner&&banner.x>=0&&banner.x+banner.width<=390,'pause banner fits phone width');
  await post('/api/teacher',{day:1,weather:0,phase:'개인 성장',market:true,paused:false},room.teacherKey);
  await page.goto(base+'/#village',{waitUntil:'domcontentloaded'});
  await page.waitForFunction(()=>window.classroomActive&&!classroomData.room.paused);
  assert.equal(await page.locator('.class-pause-banner').isVisible(),false);
  await page.waitForFunction(()=>document.querySelector('.plaza-connection')?.textContent.includes('연결됨'),{timeout:15000});
  assert(plazaPosts>0,'plaza presence resumes after teacher unpauses');
  await page.evaluate(()=>window.villageNavigate('market'));
  await page.waitForFunction(()=>document.querySelector('.market-count')?.textContent.includes('함께 있는'),{timeout:15000});
  assert(marketPosts>0,'market presence resumes after teacher unpauses');
  assert.deepEqual(errors,[]);
  console.log('PASS pause UI: five tabs, sunny farm, market/plaza quiet, resumed presence, quiz notice, 390px banner');
 }finally{await browser.close()}
})().catch(error=>{console.error(error);process.exitCode=1});
