const fs=require('fs'),assert=require('assert/strict'),{createRequire}=require('module');const {chromium}=createRequire('C:/Users/경남교육청/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/package.json')('playwright');
const base=process.env.TEST_URL||'http://127.0.0.1:8798';if(new URL(base).hostname!=='127.0.0.1')throw Error('Use isolated local test server');
(async()=>{fs.mkdirSync('test-output/plaza',{recursive:true});const results=[];const browser=await chromium.launch({channel:'msedge',headless:true});async function api(url,b,t){const r=await fetch(base+url,{method:b?'POST':'GET',headers:{'content-type':'application/json',...(t?{authorization:'Bearer '+t}:{})},...(b?{body:JSON.stringify(b)}:{})});return {status:r.status,data:await r.json()}}const setup=fs.readFileSync('private/teacher-setup.txt','utf8').trim();const room=(await api('/api/create',{size:2,setupKey:setup})).data,other=(await api('/api/create',{size:1,setupKey:setup})).data;const tokens=room.students.map(s=>s.code);let contexts=[];
try{for(const width of [1360,390]){contexts=[];const pages=[];const errors=[];for(const t of tokens){const c=await browser.newContext({viewport:{width,height:900},hasTouch:width===390});contexts.push(c);await c.addInitScript(t=>sessionStorage.setItem('village-student-token',t),t);const p=await c.newPage();p.on('pageerror',e=>errors.push(e.message));await p.goto(base+'/#village');await p.waitForFunction(()=>window.farm3DReady&&window.classroomActive);pages.push(p)}const [a,b]=pages;await a.waitForFunction(()=>document.querySelectorAll('.plaza-name').length===2);await b.waitForFunction(()=>document.querySelectorAll('.plaza-name').length===2);results.push({width,test:'two independent students see one another',pass:true});
const ids=await a.locator('.plaza-name').evaluateAll(es=>es.map(e=>({id:e.dataset.peer,self:e.classList.contains('is-me')})));const mine=ids.find(x=>x.self).id;const startX=Number(await a.locator('.plaza-name.is-me').getAttribute('data-x'));const before=(await api('/api/state',null,tokens[0])).data;
await a.locator('.plaza-tools details summary').click();await a.locator('[data-plaza-step=right]').click();await b.waitForFunction(({id,x})=>Number(document.querySelector('[data-peer="'+id+'"]')?.dataset.x)>x+.65,{id:mine,x:startX});results.push({width,test:'touch direction moves peer in other browser',pass:true});
await a.locator('.farm3d-viewport').focus();await a.keyboard.press('ArrowLeft');await b.waitForFunction(({id,x})=>Number(document.querySelector('[data-peer="'+id+'"]')?.dataset.x)<x+.35,{id:mine,x:startX});results.push({width,test:'keyboard movement visible to peer',pass:true});
await a.locator('[data-plaza-wave]').click();await b.waitForFunction(id=>document.querySelector('[data-peer="'+id+'"]')?.textContent.includes('👋'),mine);results.push({width,test:'greeting reaches peer',pass:true});
const outsider=await api('/api/plaza',{action:'visit'},other.students[0].code);assert.equal(outsider.data.visitors.length,1);assert(!outsider.data.visitors.some(p=>p.id===mine));const bad=await api('/api/plaza',{action:'move',x:100,z:-12},tokens[0]);assert.equal(bad.status,400);results.push({width,test:'classroom isolation and movement bounds',pass:true});
await a.screenshot({path:`test-output/plaza/${width}-together.png`,fullPage:true});assert(await a.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
await a.locator('[data-plaza-market]').click();await a.waitForURL('**/#market',{timeout:15000});await b.waitForFunction(id=>!document.querySelector('[data-peer="'+id+'"]'),mine);assert(await a.locator('#marketSquare').isVisible());results.push({width,test:'walk to entrance opens market and leaves plaza',pass:true});
await a.locator('.compact-tabs [data-screen=village]').click();await a.waitForFunction(()=>document.querySelectorAll('.plaza-name').length===2);await a.reload();await a.waitForFunction(()=>document.querySelectorAll('.plaza-name').length===2);const after=(await api('/api/state',null,tokens[0])).data;assert.equal(after.me.state.coins,before.me.state.coins);assert.deepEqual(after.me.state.farm,before.me.state.farm);assert.equal(errors.length,0,errors.join('\n'));results.push({width,test:'reload reconnects; farm and coins unchanged; no JS errors',pass:true});
for(const c of contexts)await c.close();contexts=[];}
}catch(e){results.push({pass:false,error:e.stack});throw e}finally{for(const c of contexts)await c.close();await browser.close();fs.writeFileSync('test-output/plaza/report.json',JSON.stringify(results,null,2));console.log(JSON.stringify(results));}})().catch(e=>{console.error(e);process.exitCode=1});
