import assert from 'node:assert/strict';import {DatabaseSync} from 'node:sqlite';import {api} from '../src/api.mjs';import {writeFile} from 'node:fs/promises';
const sql=new DatabaseSync(':memory:');sql.exec('PRAGMA foreign_keys=ON');function prepare(sqlText,args=[]){return {bind(...v){return prepare(sqlText,v)},async first(){return sql.prepare(sqlText).get(...args)||null},async all(){return {results:sql.prepare(sqlText).all(...args)}},async run(){const r=sql.prepare(sqlText).run(...args);return {meta:{changes:Number(r.changes)}}},sqlText,args}}const db={prepare,async batch(stmts){sql.exec('BEGIN');try{const out=[];for(const s of stmts)out.push(await s.run());sql.exec('COMMIT');return out}catch(e){sql.exec('ROLLBACK');throw e}}};let clock=Date.now();const realNow=Date.now;Date.now=()=>clock;
async function req(path,body,token){const r=await api(new Request('http://test'+path,{method:body?'POST':'GET',headers:{'content-type':'application/json',...(token?{authorization:'Bearer '+token}:{})},...(body?{body:JSON.stringify(body)}:{})}),{DB:db,TEACHER_SETUP_KEY:'test-key'});return {status:r.status,data:await r.json()}}const ok=r=>{assert.equal(r.status,200,JSON.stringify(r));return r.data};

try{const room=(await req('/api/create',{setupKey:'test-key',size:2})).data;const student=room.students[0].code;let n=0;const act=b=>req('/api/action',{requestId:'progress-'+(++n),...b},student);
let d=ok(await req('/api/growth',null,student));assert.deepEqual(d.progress.unlocked,[true,false,false,false,false]);assert.equal((await act({action:'plant',plot:0,crop:1})).status,400);assert.equal((await act({action:'cow_adopt'})).status,400);
for(let i=0;i<3;i++){ok(await act({action:'plant',plot:i,crop:0}));ok(await act({action:'water',plot:i}))}clock+=21000;for(let i=0;i<3;i++)ok(await act({action:'harvest',plot:i}));d=ok(await req('/api/growth',null,student));assert.equal(d.progress.count,6);assert.equal(d.progress.unlocked[1],true);ok(await act({action:'plant',plot:0,crop:1}));assert.equal((await act({action:'plant',plot:1,crop:2})).status,400);
let st=ok(await req('/api/state',null,student));st.me.state.farm.picked=80;st.me.state.coins=200;sql.prepare('UPDATE players SET state=? WHERE id=?').run(JSON.stringify(st.me.state),st.me.id);
const adopt={action:'cow_adopt',requestId:'adopt-once'};ok(await req('/api/action',adopt,student));ok(await req('/api/action',adopt,student));st=ok(await req('/api/state',null,student));assert.equal(st.me.state.coins,100);ok(await act({action:'cow_feed'}));ok(await act({action:'cow_water'}));assert.equal((await act({action:'cow_milk'})).status,400);clock+=21000;ok(await act({action:'cow_milk'}));assert.equal((await act({action:'cow_feed'})).status,400);st=ok(await req('/api/state',null,student));assert.equal(st.me.state.stock[1],2);sql.prepare('UPDATE rooms SET day=day+1 WHERE id=?').run(st.room.id);ok(await act({action:'cow_feed'}));
// Grandfather a crop already cultivated without erasing the old inventory.
st=ok(await req('/api/state',null,student));st.me.state.farm.picked=0;st.me.state.garden.harvested[4]=2;sql.prepare('UPDATE players SET state=? WHERE id=?').run(JSON.stringify(st.me.state),st.me.id);d=ok(await req('/api/growth',null,student));assert.equal(d.progress.unlocked[4],true);
console.log('PASS: starter seed lock, actual harvest unlock, cow eligibility, idempotent adoption, care timer, daily milk, legacy crop preservation');
}finally{Date.now=realNow;sql.close()}

