import assert from 'node:assert/strict';import {DatabaseSync} from 'node:sqlite';import {api} from '../src/api.mjs';import {writeFile} from 'node:fs/promises';
const sql=new DatabaseSync(':memory:');sql.exec('PRAGMA foreign_keys=ON');function prepare(sqlText,args=[]){return {bind(...v){return prepare(sqlText,v)},async first(){return sql.prepare(sqlText).get(...args)||null},async all(){return {results:sql.prepare(sqlText).all(...args)}},async run(){const r=sql.prepare(sqlText).run(...args);return {meta:{changes:Number(r.changes)}}},sqlText,args}}const db={prepare,async batch(stmts){sql.exec('BEGIN');try{const out=[];for(const s of stmts)out.push(await s.run());sql.exec('COMMIT');return out}catch(e){sql.exec('ROLLBACK');throw e}}};let clock=Date.now();const realNow=Date.now;Date.now=()=>clock;
async function req(path,body,token){const r=await api(new Request('http://test'+path,{method:body?'POST':'GET',headers:{'content-type':'application/json',...(token?{authorization:'Bearer '+token}:{})},...(body?{body:JSON.stringify(body)}:{})}),{DB:db,TEACHER_SETUP_KEY:'test-key'});return {status:r.status,data:await r.json()}}const ok=r=>{assert.equal(r.status,200,JSON.stringify(r));return r.data};
try{const made=await req('/api/create',{setupKey:'test-key',size:32});assert.equal(made.status,201);const room=made.data,t=room.teacherKey,ss=room.students;const home=ok(await req('/api/campus',null,ss[0].code)).home;const study=(i,action,extra={})=>req('/api/campus/study',{action,id:'seat-session-'+i,goal:'좌석 검증',plan:15,seat:'도서관',...extra},ss[i].code);
for(let i=0;i<30;i++)ok(await study(i,'start',{studyRoom:home,seatNumber:i+1}));let d=ok(await req('/api/campus',null,t));assert.equal(d.seats.length,30);assert.equal(d.rooms[0].occupied,30);assert.equal((await study(30,'start',{studyRoom:home,seatNumber:1})).status,409);assert.equal((await study(30,'start')).status,409);assert.equal(sql.prepare("SELECT count(*) n FROM study_sessions WHERE room=?").get(home).n,30,'full room leaves no ghost sessions');
ok(await study(0,'pause'));assert.equal(ok(await req('/api/campus',null,ss[0].code)).current.seatNumber,1);assert.equal((await study(30,'start',{seatNumber:1})).status,409);ok(await study(1,'cancel'));ok(await study(30,'start',{seatNumber:2}));assert.equal(ok(await req('/api/campus',null,ss[30].code)).current.seatNumber,2);
clock+=900001;d=ok(await req('/api/campus',null,ss[0].code));assert.equal(d.current.seatNumber,null);assert.equal(d.seats.length,0);ok(await study(31,'start',{seatNumber:1}));assert.equal((await study(0,'resume')).status,409);ok(await study(0,'claim',{seatNumber:3}));ok(await study(0,'resume'));assert.equal(ok(await req('/api/campus',null,ss[0].code)).current.seatNumber,3);assert.equal((await study(0,'claim',{seatNumber:1})).status,409);assert.equal(ok(await req('/api/campus',null,ss[0].code)).current.seatNumber,3,'failed change keeps original seat');
assert.equal((await req('/api/campus/seats/release',{number:3},ss[1].code)).status,403);ok(await req('/api/campus/seats/release',{number:3},t));d=ok(await req('/api/campus',null,ss[0].code));assert.equal(d.current.status,'paused');assert.equal(d.current.seatNumber,null);assert.equal((await study(0,'resume')).status,409);ok(await study(0,'finish',{minutes:0,reflection:'기록은 남아요'}));assert.equal(ok(await req('/api/campus',null,ss[0].code)).history[0].reflection,'기록은 남아요');
const other=(await req('/api/create',{setupKey:'test-key',size:2})).data;ok(await req('/api/campus/link',{code:other.roomCode,teacherKey:other.teacherKey,label:'이웃 반'},t));const target=ok(await req('/api/campus',null,other.teacherKey)).home;
assert.equal((await study(0,'start',{id:'visit-session',studyRoom:target,seatNumber:1})).status,403);ok(await req('/api/campus/settings',{travel:true,library:true,label:'우리 반'},t));assert.equal((await study(0,'start',{id:'visit-session',studyRoom:target,seatNumber:1})).status,403);ok(await req('/api/campus/passport',{answer:1},ss[0].code));d=ok(await study(0,'start',{id:'visit-session',studyRoom:target,seatNumber:1}));assert.equal(d.current.studyRoom,target);assert.equal(d.home,home);assert.equal(ok(await req('/api/campus?classroom='+target,null,t)).records.length,0,'visiting study record stays in home class');
await writeFile('test-output/seats-unit-report.json',JSON.stringify({passed:true,checks:['30-seat capacity','occupied seat rejected','no orphan full-room session','pause reserves seat','cancel returns seat','offline 15-minute expiry','expired resume denied','reclaim another seat','failed move rolls back','teacher release retains record','teacher authorization','passport/travel gate','visitor home records retained']},null,2));console.log('PASS: 13 seat lifecycle, capacity and authorization checks');}finally{Date.now=realNow;sql.close()}
