const fs=require('fs'),assert=require('assert/strict'),{createRequire}=require('module');
const {chromium}=createRequire('C:/Users/경남교육청/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/package.json')('playwright');
const base=process.env.TEST_URL||'http://127.0.0.1:8801';fs.mkdirSync('test-output/smart-farm',{recursive:true});
(async()=>{const browser=await chromium.launch({channel:'msedge',headless:true}),results=[];
try{for(const width of [1366,390]){const create=await fetch(base+'/api/create',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({size:1,setupKey:fs.readFileSync('private/teacher-setup.txt','utf8').trim()})});assert(create.ok);const token=(await create.json()).students[0].code;
 const context=await browser.newContext({viewport:{width,height:width===390?844:768},hasTouch:width===390});await context.addInitScript(t=>sessionStorage.setItem('village-student-token',t),token);const page=await context.newPage(),errors=[],assets=[];page.on('pageerror',e=>errors.push(e.message));page.on('response',r=>{if(r.url().includes('/assets/smart-farm/')&&r.url().endsWith('.glb'))assets.push({name:r.url().split('/').pop(),status:r.status()})});await page.goto(base+'/#farm');await page.waitForFunction(()=>window.farm3DReady&&window.classroomActive);await page.locator('.smart-farm-label:visible').waitFor({timeout:15000});
 const inspect=async(name,fn)=>{try{await fn();results.push({width,name,pass:true})}catch(e){results.push({width,name,pass:false,error:e.message})}};
 await inspect('three models load and label fits map',async()=>{await page.waitForTimeout(350);assert.deepEqual(assets.map(a=>a.name).sort(),['farm-robot.glb','irrigation-station.glb','moisture-sensor.glb']);assert(assets.every(a=>a.status===200));const b=await page.locator('.smart-farm-label').boundingBox(),m=await page.locator('.farm3d-viewport').boundingBox();assert(b&&b.x>=m.x&&b.y>=m.y&&b.x+b.width<=m.x+m.width&&b.y+b.height<=m.y+m.height)});
 await page.locator('[data-bed3d="0"]').click();await page.locator('.selected-bed-action').click();await page.waitForFunction(()=>state.farm.plots[0].seeded&&!window.classroomSaving);await page.waitForFunction(()=>!document.querySelector('.selected-bed-action').disabled);await page.locator('.smart-farm-bed-button').click();await inspect('measurement is labeled simulation and panel fits map',async()=>{await page.locator('.smart-farm-measure').click({timeout:3000});assert.match(await page.locator('.smart-farm-panel').textContent(),/건조 24%/);assert.match(await page.locator('.smart-farm-panel').textContent(),/교육용 추정치/);await page.locator('.smart-farm-water').waitFor({state:'visible'});await page.waitForFunction(()=>!document.querySelector('.smart-farm-water').disabled);const b=await page.locator('.smart-farm-panel').boundingBox(),m=await page.locator('.farm3d-viewport').boundingBox();assert(b&&b.x>=m.x&&b.y>=m.y&&b.x+b.width<=m.x+m.width&&b.y+b.height<=m.y+m.height);await page.screenshot({path:`test-output/smart-farm/panel-${width}.png`})});
 await page.locator('.smart-farm-water').click({timeout:3000});await page.waitForFunction(()=>state.farm.plots[0].wateredAt>0);await inspect('robot watering uses saved plot action',async()=>{assert.equal(await page.locator('.smart-farm-panel:visible').count(),0);assert.match(await page.locator('[data-bed3d="0"]').getAttribute('aria-label'),/새싹|성장|수확/);assert.equal(errors.length,0,errors.join(';'))});
 await page.reload();await page.waitForFunction(()=>window.farm3DReady&&window.classroomActive);await inspect('water persists after reload',async()=>assert(await page.evaluate(()=>state.farm.plots[0].wateredAt>0)));
 await page.locator('.compact-tabs [data-screen=village]').click();await inspect('smart farm controls stay in farm',async()=>assert.equal(await page.locator('.smart-farm-label:visible,.smart-farm-panel:visible').count(),0));await context.close();}}
finally{await browser.close();fs.mkdirSync('test-output/smart-farm',{recursive:true});fs.writeFileSync('test-output/smart-farm/results.json',JSON.stringify(results,null,2));console.log(JSON.stringify(results));process.exitCode=results.some(r=>!r.pass)?1:0}})().catch(e=>{console.error(e);process.exitCode=1});
