import assert from 'node:assert/strict';import {readFile,writeFile} from 'node:fs/promises';
const base=process.env.TEST_URL||'http://127.0.0.1:8787',key=(await readFile('private/teacher-setup.txt','utf8')).trim();
async function req(path,body,token){const r=await fetch(base+path,{method:body?'POST':'GET',headers:{'content-type':'application/json',...(token?{authorization:'Bearer '+token}:{}),...(process.env.SITES_AUTH?{'OAI-Sites-Authorization':'Bearer '+process.env.SITES_AUTH}:{})},...(body?{body:JSON.stringify(body)}:{})});return {status:r.status,data:await r.json()}}
let seq=0;const act=(s,action,extra={},id)=>req('/api/action',{action,...extra,requestId:id||'story-test-'+(++seq)},s.code);const ok=r=>{assert.equal(r.status,200,JSON.stringify(r));return r.data};
const made=await req('/api/create',{setupKey:key,size:16});assert.equal(made.status,201,JSON.stringify(made));const room=made.data,ss=room.students;
assert.equal((await req('/api/story/start',{participants:9},ss[0].code)).status,403);assert.equal((await req('/api/story/start',{participants:17},room.teacherKey)).status,400);
assert.equal((await req('/api/story/start',{participants:0},room.teacherKey)).status,400);
let d=ok(await req('/api/story/start',{participants:9},room.teacherKey));assert.equal(d.mission.target,2);assert.equal(d.mission.goal,3);assert.equal(d.room.weather,3);assert.equal(d.room.market,false);
const started=d.mission.started;assert.equal(ok(await req('/api/story/start',{participants:16},room.teacherKey)).mission.started,started);
assert.equal((await act(ss[0],'mission_task',{item:2,answer:2})).status,409);assert.equal((await act(ss[0],'mission_donate',{item:0,qty:1})).status,409);
assert.equal((await act(ss[0],'mission_task',{item:0,answer:0})).status,400);let one=ok(await act(ss[0],'mission_task',{item:0,answer:1},'road-replay-001'));assert.equal(one.me.state.coins,90);assert.equal(one.mission.counts[0],1);assert.equal(one.room.market,false);
const repeats=await Promise.all(Array.from({length:6},()=>act(ss[0],'mission_task',{item:0,answer:1},'road-replay-001')));assert(repeats.every(r=>r.status===200));assert.equal(repeats[0].data.me.state.coins,90);assert.equal((await act(ss[0],'mission_task',{item:0,answer:1})).status,409);
ok(await act(ss[1],'mission_task',{item:0,answer:1}));ok(await act(ss[2],'mission_task',{item:1,answer:0}));d=ok(await act(ss[3],'mission_task',{item:1,answer:0}));assert.equal(d.room.weather,4);assert.equal(d.room.market,true);
const settings={day:1,weather:4,market:true,phase:'협력',paused:true};ok(await req('/api/teacher',settings,room.teacherKey));assert.equal((await act(ss[0],'mission_task',{item:1,answer:0})).status,423);ok(await req('/api/teacher',{...settings,paused:false},room.teacherKey));
for(let i=0;i<8;i++)ok(await act(ss[i],'produce'));
for(let i=0;i<4;i++)ok(await act(ss[i],'mission_donate',{item:i,qty:2}));
// Two different holders compete for the final unit of the same ingredient.
ok(await act(ss[8],'produce'));const race=await Promise.all([act(ss[4],'mission_donate',{item:0,qty:1}),act(ss[8],'mission_donate',{item:0,qty:1})]);assert.equal(race.filter(r=>r.status===200).length,1,JSON.stringify(race));assert.equal(race.filter(r=>r.status===409).length,1);
for(let i=1;i<4;i++)ok(await act(ss[i+4],'mission_donate',{item:i,qty:1}));
assert.equal((await act(ss[0],'mission_task',{item:3,answer:1})).status,409);ok(await act(ss[0],'mission_task',{item:2,answer:2}));assert.equal((await act(ss[0],'mission_task',{item:3,answer:1})).status,409);ok(await act(ss[1],'mission_task',{item:2,answer:2}));d=ok(await act(ss[0],'mission_task',{item:3,answer:1}));assert.equal(d.mission.completed,0);d=ok(await act(ss[1],'mission_task',{item:3,answer:1}));assert(d.mission.completed>0);assert.deepEqual(d.mission.food,[3,3,3,3]);assert.deepEqual(d.mission.counts,[2,2,2,2]);assert.equal(d.mission.revision,20);
const fresh=ok(await req('/api/state',null,room.teacherKey));assert.equal(fresh.mission.completed,d.mission.completed);assert.equal(fresh.players.reduce((n,p)=>n+p.stock.reduce((a,b)=>a+b,0),0),6);assert.equal(fresh.players.reduce((n,p)=>n+p.coins,0),16*80+80);
const other=await req('/api/create',{setupKey:key,size:1});assert.equal((await act(other.data.students[0],'mission_task',{item:0,answer:1})).status,409);
await writeFile('test-output/story-api-report.json',JSON.stringify({passed:true,environment:base,checks:['teacher start and goals','wrong answer and locked stages','idempotent reward','distinct participants quorum','pause','concurrent last donation','stock conservation','completion and persistence','class isolation'],revision:d.mission.revision},null,2));console.log('PASS: story API, 10 checks; stock and rewards conserved');

const loadRoom=(await req('/api/create',{setupKey:key,size:120})).data;ok(await req('/api/story/start',{participants:120},loadRoom.teacherKey));const t=Date.now();const load=await Promise.all(loadRoom.students.map(s=>act(s,'mission_task',{item:0,answer:1})));assert(load.every(r=>r.status===200),JSON.stringify(load.filter(r=>r.status!==200)));const written=Date.now()-t;const t2=Date.now();const reads=await Promise.all(loadRoom.students.map(s=>req('/api/state',null,s.code)));assert(reads.every(r=>r.status===200&&r.data.mission.counts[0]===120));await writeFile('test-output/story-load-report.json',JSON.stringify({passed:true,environment:base,requests:120,concurrentStoryWritesWallMs:written,concurrentStoryReadsWallMs:Date.now()-t2,note:'HTTP requests from one machine; not 120 physical browsers'},null,2));console.log('PASS: 120 concurrent active-story contributions and snapshots');
