import {schema} from './schema.mjs';
const ready=new WeakMap();
const encoder=new TextEncoder();
const json=(data,status=200)=>new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store','x-content-type-options':'nosniff'}});
const err=(message,status=400)=>{throw Object.assign(new Error(message),{status})};
const int=(n,min,max)=>{if(!Number.isInteger(n)||n<min||n>max)err('수량이나 선택을 확인해 주세요.');return n};
const random=(n=16)=>Array.from(crypto.getRandomValues(new Uint8Array(n)),x=>x.toString(16).padStart(2,'0')).join('');
const hash=async s=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',encoder.encode(s))),x=>x.toString(16).padStart(2,'0')).join('');
const initial=(i)=>({job:i%4,name:`학생 ${String(i+1).padStart(3,'0')}`,coins:80,stock:[0,0,0,0],level:1,quizDay:0,knowledge:false,road:false,repaired:false,repairDay:0,donated:[0,0,0,0],completed:false,history:['학급 마을에 입장했어요.'],place:'work',farm:{plots:Array.from({length:6},()=>({seeded:false,wateredAt:0})),picked:0,sold:0},dailyProduction:0,productionDay:0});
const factors=[[1,1,1,1],[1.25,1.2,1.3,1.1],[1.1,1.15,.9,1.2],[1.4,1.35,1.2,1.5],[1.1,1.05,1.1,1.2],[.8,.95,.8,1]];
function price(room,item){return Math.round([10,14,12,16][item]*factors[room.weather][item])}
function note(s,t){s.history=[t,...s.history].slice(0,20)}
async function init(db){if(!ready.has(db)){const p=db.batch(schema.map(sql=>db.prepare(sql))).catch(e=>{ready.delete(db);throw e});ready.set(db,p)}await ready.get(db)}
async function body(req){if(Number(req.headers.get('content-length'))>16384)err('요청이 너무 큽니다.',413);const txt=await req.text();if(txt.length>16384)err('요청이 너무 큽니다.',413);try{return JSON.parse(txt||'{}')}catch{err('요청 형식을 확인해 주세요.')}}
async function limiter(db,key,now,max=15){await db.prepare('INSERT INTO attempts(key,count,expires) VALUES(?,1,?) ON CONFLICT(key) DO UPDATE SET count=CASE WHEN expires<? THEN 1 ELSE count+1 END,expires=CASE WHEN expires<? THEN excluded.expires ELSE expires END').bind(key,now+60000,now,now).run();const row=await db.prepare('SELECT count FROM attempts WHERE key=?').bind(key).first();if(row.count>max)err('잠시 후 다시 시도해 주세요.',429)}
async function auth(req,db){const token=(req.headers.get('authorization')||'').replace(/^Bearer /,'');if(!/^[a-f0-9]{24,64}$/.test(token))err('입장 코드를 입력해 주세요.',401);const h=await hash(token),p=await db.prepare('SELECT * FROM players WHERE token_hash=?').bind(h).first();if(p)return {player:p,room:await db.prepare('SELECT * FROM rooms WHERE id=?').bind(p.room).first()};const r=await db.prepare('SELECT * FROM rooms WHERE teacher_hash=?').bind(h).first();if(r)return {teacher:true,room:r};err('입장 정보가 만료되었어요. 다시 입장해 주세요.',401)}
function safeRoom(r){return {id:r.id,code:r.code,day:r.day,weather:r.weather,market:!!r.market,paused:!!r.paused,phase:r.phase,coop:JSON.parse(r.coop),goal:r.goal,version:r.version}}
async function snapshot(db,a){const players=await db.prepare('SELECT id,name,state,last_seen FROM players WHERE room=? ORDER BY name').bind(a.room.id).all();const offers=await db.prepare("SELECT o.*,p.name seller_name FROM offers o JOIN players p ON p.id=o.seller WHERE o.room=? AND o.status='open' ORDER BY o.created DESC LIMIT 200").bind(a.room.id).all();return {room:safeRoom(a.room),me:a.player?{id:a.player.id,state:JSON.parse(a.player.state),version:a.player.version}:null,teacher:!!a.teacher,players:players.results.map(p=>{const s=JSON.parse(p.state);return {id:p.id,name:p.name,job:s.job,place:s.place,plots:s.farm.plots.length,picked:s.farm.picked,online:Date.now()-p.last_seen<40000,...(a.teacher?{coins:s.coins,stock:s.stock,donated:s.donated}: {})}}),offers:offers.results,serverTime:Date.now()}}
async function mutation(db,a,input){const room=a.room,p=a.player;if(!p)err('학생으로 입장해 주세요.',403);if(!/^[a-zA-Z0-9_-]{8,80}$/.test(input.requestId||''))err('저장 식별자가 없습니다. 새로고침 후 다시 시도해 주세요.');const cmdId=p.id+':'+input.requestId;const prior=await db.prepare('SELECT id FROM commands WHERE id=? AND actor=?').bind(cmdId,p.id).first();if(prior)return {duplicate:true};if(room.paused&&input.action!=='cancel')err('교사가 수업을 일시정지했어요.',423);const s=JSON.parse(p.state);const kind=input.action;let partner=null,s2=null,v2=null,offerId=null,offerData=null,item=null,qty=null;const now=Date.now();
if(['plant','water','harvest','produce'].includes(kind)&&room.weather===3&&s.repairDay!==room.day)err('폭우 안전 미션을 먼저 해결해 주세요.');
if(['plant','water','harvest'].includes(kind)){const index=int(input.plot,0,s.farm.plots.length-1),plot=s.farm.plots[index];if(kind==='plant'){if(plot.seeded)err('이미 씨앗이 심어져 있어요.',409);plot.seeded=true;note(s,`${index+1}번 밭에 씨를 심었어요.`)}if(kind==='water'){if(!plot.seeded||plot.wateredAt)err('물을 줄 수 있는 상태가 아니에요.',409);plot.wateredAt=now;note(s,`${index+1}번 밭에 물을 줬어요.`)}if(kind==='harvest'){if(!plot.wateredAt||now-plot.wateredAt<20000)err('아직 작물이 자라고 있어요.',409);s.stock[0]+=s.level+1;s.farm.picked+=s.level+1;s.farm.plots[index]={seeded:false,wateredAt:0};note(s,'수확한 상추를 보관소에 넣었어요.')}}
else if(kind==='produce'){if(s.productionDay!==room.day){s.productionDay=room.day;s.dailyProduction=0}if(s.dailyProduction>=3)err('오늘 생산을 모두 마쳤어요. 장터나 공동 미션에 참여해 주세요.');s.dailyProduction++;s.stock[s.job]+=s.level+1;note(s,'내 직업의 생산물을 만들었어요.')}
else if(kind==='sell'){item=int(input.item,0,3);qty=int(input.qty,1,1000);if(s.stock[item]<qty)err('보관한 물건이 부족해요.');const unit=room.market?price(room,item):Math.floor(price(room,item)*.8);s.stock[item]-=qty;s.coins+=qty*unit;s.farm.sold+=qty*unit;note(s,`물건 ${qty}개를 ${qty*unit}코인에 판매했어요.`)}
else if(kind==='expand'){if(s.farm.plots.length>=12)err('밭 확장을 모두 마쳤어요.');const cost=s.farm.plots.length===6?40:s.farm.plots.length===8?60:80;if(s.coins<cost)err('코인이 부족해요.');s.coins-=cost;s.farm.plots.push({seeded:false,wateredAt:0},{seeded:false,wateredAt:0});note(s,'밭이 2칸 늘어났어요.')}
else if(kind==='quiz'){if(s.quizDay===room.day)err('오늘 보너스는 이미 받았어요.');if(input.answer!==[0,1,2,0][s.job])err('다시 생각해 보세요.');s.quizDay=room.day;s.knowledge=true;s.coins+=20;note(s,'직업 탐험을 마치고 20코인을 받았어요.')}
else if(kind==='repair'){if(input.answer!==1)err('안전한 대응을 골라 주세요.');s.repairDay=room.day;s.repaired=true;note(s,'전력 설비 기술자와 안전하게 문제를 해결했어요.')}
else if(kind==='upgrade'){if(!s.knowledge||s.level>=2||s.coins<60)err('직업 탐험과 60코인이 필요해요.');s.coins-=60;s.level=2}
else if(kind==='job'){if(s.farm.picked>0||s.dailyProduction>0)err('역할 변경은 첫 생산 전에 할 수 있어요.');s.job=int(input.job,0,3)}
else if(kind==='place'){if(!['work','market','season','village'].includes(input.place))err('이동할 장소를 확인해 주세요.');s.place=input.place}
else if(kind==='offer'){if(!room.market)err('장터가 닫혀 있어요.');const count=await db.prepare("SELECT count(*) n FROM offers WHERE seller=? AND status='open'").bind(p.id).first();if(count.n>=3)err('열린 교환 제안은 3개까지 가능해요.');offerData={giveItem:int(input.giveItem,0,3),giveQty:int(input.giveQty,1,50),wantItem:int(input.wantItem,0,3),wantQty:int(input.wantQty,1,50)};if(offerData.giveItem===offerData.wantItem)err('서로 다른 물건을 선택해 주세요.');if(s.stock[offerData.giveItem]<offerData.giveQty)err('제안할 물건이 부족해요.');s.stock[offerData.giveItem]-=offerData.giveQty;offerId=random();note(s,'교환할 물건을 장터에 맡겼어요.')}
else if(kind==='accept'||kind==='cancel'){const o=await db.prepare('SELECT * FROM offers WHERE id=? AND room=?').bind(String(input.offer),room.id).first();if(!o||o.status!=='open')err('이미 완료되거나 취소된 교환이에요.',409);offerId=o.id;if(kind==='cancel'){if(o.seller!==p.id)err('내 제안만 취소할 수 있어요.',403);s.stock[o.give_item]+=o.give_qty;note(s,'제안을 취소하고 물건을 돌려받았어요.')}else{if(!room.market)err('장터가 닫혀 있어요.');if(o.seller===p.id)err('자신의 제안은 수락할 수 없어요.');if(s.stock[o.want_item]<o.want_qty)err('교환할 물건이 부족해요.');const other=await db.prepare('SELECT * FROM players WHERE id=? AND room=?').bind(o.seller,room.id).first();if(!other)err('거래 상대를 찾을 수 없어요.');partner=other.id;v2=other.version;s2=JSON.parse(other.state);s.stock[o.want_item]-=o.want_qty;s.stock[o.give_item]+=o.give_qty;s2.stock[o.want_item]+=o.want_qty;note(s,`${other.name}과 물건을 교환했어요.`);note(s2,`${p.name}과 물건을 교환했어요.`)}}
else if(kind==='donate'){if(room.phase!=='협력')err('아직 협력 시즌이 아니에요.');item=int(input.item,0,3);qty=int(input.qty||1,1,50);if(s.stock[item]<qty)err('보탤 물건이 부족해요.');s.stock[item]-=qty;s.donated[item]+=qty;note(s,`공동 식탁에 물건 ${qty}개를 보탰어요.`)}else err('지원하지 않는 활동입니다.');
await db.prepare('INSERT INTO commands(id,actor,room,kind,version1,version2,partner,state1,state2,room_version,offer,offer_data,item,qty,created) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)').bind(cmdId,p.id,room.id,kind,p.version,v2,partner,JSON.stringify(s),s2?JSON.stringify(s2):null,room.version,offerId,offerData?JSON.stringify(offerData):null,item,qty,now).run();return {ok:true}}
export async function api(req,env){try{const u=new URL(req.url);if(!u.pathname.startsWith('/api/'))return null;const db=env.DB;if(!db)return json({error:'공동 플레이 서버가 연결되지 않았습니다.'},503);await init(db);if(u.pathname==='/api/health')return json({ok:true,storage:'server',version:6});const origin=req.headers.get('origin');if(origin&&origin!==u.origin)err('다른 사이트의 요청은 허용되지 않습니다.',403);const b=req.method==='POST'?await body(req):{};
if(u.pathname==='/api/create'&&req.method==='POST'){if(!env.TEACHER_SETUP_KEY||await hash(String(b.setupKey||''))!==await hash(env.TEACHER_SETUP_KEY))err('교사 개설키를 확인해 주세요.',403);const size=int(b.size,1,120),id=random(),code=random(3).toUpperCase(),teacherKey=random(24),created=Date.now();const statements=[db.prepare('INSERT INTO rooms(id,code,teacher_hash,goal,created) VALUES(?,?,?,?,?)').bind(id,code,await hash(teacherKey),Math.max(2,Math.ceil(size/4)),created)];const students=[];for(let i=0;i<size;i++){const token=random(12),pid=random(),s=initial(i);students.push({name:s.name,code:token,role:s.job});statements.push(db.prepare('INSERT INTO players(id,room,name,token_hash,state) VALUES(?,?,?,?,?)').bind(pid,id,s.name,await hash(token),JSON.stringify(s)))}await db.batch(statements);return json({roomCode:code,teacherKey,students},201)}
if(u.pathname==='/api/join'&&req.method==='POST'){const roomCode=String(b.roomCode||'').trim().toUpperCase(),token=String(b.code||'').trim().toLowerCase();await limiter(db,'join:'+await hash((req.headers.get('cf-connecting-ip')||'local')+roomCode),Date.now(),160);const a=await auth(new Request(req.url,{headers:{authorization:'Bearer '+token}}),db);if(a.room.code!==roomCode)err('학급 코드와 입장 코드를 확인해 주세요.',401);if(a.player)await db.prepare('UPDATE players SET last_seen=? WHERE id=?').bind(Date.now(),a.player.id).run();return json({...await snapshot(db,a),token})}
const a=await auth(req,db);if(u.pathname==='/api/state'&&req.method==='GET'){if(a.player)await db.prepare('UPDATE players SET last_seen=? WHERE id=? AND last_seen<?').bind(Date.now(),a.player.id,Date.now()-20000).run();return json(await snapshot(db,a))}
if(u.pathname==='/api/action'&&req.method==='POST'){if(!a.player)err('학생으로 입장해 주세요.',403);let result;for(let attempt=0;attempt<5;attempt++){const fresh=attempt?await auth(req,db):a;try{result=await mutation(db,fresh,b);break}catch(e){if(/STATE_CHANGED|ROOM_CHANGED|UNIQUE constraint failed: commands.id/.test(e.message)&&attempt<4)continue;throw e}}const updated=await auth(req,db);return json({...result,...await snapshot(db,updated)})}
if(u.pathname==='/api/teacher'&&req.method==='POST'){if(!a.teacher)err('교사만 사용할 수 있어요.',403);const day=int(b.day,1,365),weather=int(b.weather,0,5);if(!['개인 성장','협력'].includes(b.phase))err('시즌을 선택해 주세요.');await db.prepare('UPDATE rooms SET day=?,weather=?,market=?,paused=?,phase=?,version=version+1 WHERE id=?').bind(day,weather,b.market?1:0,b.paused?1:0,b.phase,a.room.id).run();return json(await snapshot(db,await auth(req,db)))}
return json({error:'경로를 찾을 수 없습니다.'},404)}catch(e){const text=String(e.message);const conflict=/STATE_CHANGED|ROOM_CHANGED|OFFER_CLOSED|MARKET_CLOSED|CHECK constraint/.test(text);return json({error:conflict?'상태가 바뀌었어요. 새로 반영된 내용을 보고 다시 시도해 주세요.':e.status?text:'처리하지 못했어요. 잠시 후 같은 요청을 다시 시도해 주세요.'},e.status||(conflict?409:500))}}
