const fail=(message,status=400)=>{throw Object.assign(new Error(message),{status})};
const hash=async s=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s))),n=>n.toString(16).padStart(2,'0')).join('');
const clean=(v,max)=>String(v||'').trim().slice(0,max);
export const campusSchema=[
`CREATE TABLE IF NOT EXISTS campuses(id TEXT PRIMARY KEY,travel INTEGER NOT NULL DEFAULT 0,library INTEGER NOT NULL DEFAULT 1)`,
`CREATE TABLE IF NOT EXISTS campus_rooms(room TEXT PRIMARY KEY REFERENCES rooms(id),campus TEXT NOT NULL REFERENCES campuses(id),label TEXT NOT NULL)`,
`CREATE INDEX IF NOT EXISTS campus_members ON campus_rooms(campus)`,
`CREATE TRIGGER IF NOT EXISTS campus_limit BEFORE INSERT ON campus_rooms WHEN NOT EXISTS(SELECT 1 FROM campus_rooms WHERE room=NEW.room) AND (SELECT count(*) FROM campus_rooms WHERE campus=NEW.campus)>=4 BEGIN SELECT RAISE(ABORT,'CAMPUS_FULL'); END`,
`CREATE TRIGGER IF NOT EXISTS campus_ownership BEFORE INSERT ON campus_rooms WHEN EXISTS(SELECT 1 FROM campus_rooms WHERE room=NEW.room AND campus<>NEW.campus) BEGIN SELECT RAISE(ABORT,'CAMPUS_OWNERSHIP'); END`,
`CREATE TABLE IF NOT EXISTS passports(actor TEXT PRIMARY KEY,issued INTEGER NOT NULL)`,
`CREATE TABLE IF NOT EXISTS stamps(actor TEXT NOT NULL,destination TEXT NOT NULL,visited INTEGER NOT NULL,PRIMARY KEY(actor,destination))`,
`CREATE TABLE IF NOT EXISTS study_sessions(id TEXT PRIMARY KEY,actor TEXT NOT NULL,room TEXT NOT NULL,goal TEXT NOT NULL,plan INTEGER NOT NULL,seat TEXT NOT NULL,status TEXT NOT NULL,elapsed INTEGER NOT NULL DEFAULT 0,tick INTEGER NOT NULL,version INTEGER NOT NULL DEFAULT 0,created INTEGER NOT NULL,ended INTEGER,reflection TEXT NOT NULL DEFAULT '',reported INTEGER NOT NULL DEFAULT 0,points INTEGER NOT NULL DEFAULT 0,day TEXT)`,
`CREATE UNIQUE INDEX IF NOT EXISTS one_study_session ON study_sessions(actor) WHERE status IN ('active','paused')`,
`CREATE INDEX IF NOT EXISTS study_room ON study_sessions(room,status,tick)`,
`CREATE INDEX IF NOT EXISTS study_actor ON study_sessions(actor,created)`,
`CREATE INDEX IF NOT EXISTS study_daily ON study_sessions(actor,day,status)`
];
async function membership(db,room){return db.prepare('SELECT cr.*,c.travel,c.library FROM campus_rooms cr JOIN campuses c ON c.id=cr.campus WHERE cr.room=?').bind(room).first()}
export async function managedAuth(db,a,id){if(!id||id===a.room.id)return a;if(!a.teacher)fail('교사만 학급을 전환할 수 있어요.',403);const row=await db.prepare('SELECT r.* FROM rooms r JOIN campus_rooms x ON x.room=r.id JOIN campus_rooms y ON y.campus=x.campus WHERE y.room=? AND r.id=?').bind(a.room.id,id).first();if(!row)fail('관리 권한이 없는 학급이에요.',403);return {...a,room:row}}
async function board(db,a){const member=await membership(db,a.room.id),now=Date.now();const rooms=member?(await db.prepare('SELECT r.id,r.code,c.label,(SELECT count(*) FROM players WHERE room=r.id) students FROM campus_rooms c JOIN rooms r ON r.id=c.room WHERE c.campus=? ORDER BY c.label').bind(member.campus).all()).results:[{id:a.room.id,code:a.room.code,label:'우리 반 마을',students:(await db.prepare('SELECT count(*) n FROM players WHERE room=?').bind(a.room.id).first()).n}];
const roomIds=rooms.map(r=>r.id),marks=roomIds.map(()=>'?').join(',');
const peers=(await db.prepare(`SELECT p.id,json_extract(p.state,'$.name') name,s.room,s.seat,s.status,s.tick FROM study_sessions s JOIN players p ON p.id=s.actor WHERE s.room IN (${marks}) AND s.status IN ('active','paused') AND s.tick>? LIMIT 120`).bind(...roomIds,now-90000).all()).results.map(p=>({id:p.id,name:p.name,room:p.room,seat:p.seat,status:p.status==='active'&&now-p.tick<=45000?'집중 중':'쉬는 중'}));
if(a.teacher){const records=(await db.prepare("SELECT s.*,p.name accountName,json_extract(p.state,'$.name') name FROM study_sessions s JOIN players p ON p.id=s.actor WHERE s.room=? ORDER BY s.created DESC LIMIT 240").bind(a.room.id).all()).results;return {rooms,travel:!!member?.travel,library:member?!!member.library:true,home:a.room.id,peers,records}}
const [passport,stamps,current,history,total]=await Promise.all([db.prepare('SELECT issued FROM passports WHERE actor=?').bind(a.player.id).first(),db.prepare('SELECT destination,visited FROM stamps WHERE actor=?').bind(a.player.id).all(),db.prepare("SELECT * FROM study_sessions WHERE actor=? AND status IN ('active','paused')").bind(a.player.id).first(),db.prepare("SELECT * FROM study_sessions WHERE actor=? AND status IN ('finished','cancelled') ORDER BY created DESC LIMIT 12").bind(a.player.id).all(),db.prepare('SELECT coalesce(sum(points),0) n FROM study_sessions WHERE actor=?').bind(a.player.id).first()]);return {rooms,travel:!!member?.travel,library:member?!!member.library:true,home:a.room.id,name:JSON.parse(a.player.state).name,paused:!!a.room.paused,passport:passport?.issued||0,stamps:stamps.results,current,history:history.results,points:total.n,peers,serverTime:now}}
export async function campusApi(db,a,path,b,method){if(path==='/api/campus'&&method==='GET')return board(db,a);
if(path==='/api/campus/link'&&method==='POST'){if(!a.teacher)fail('교사만 학급을 연결할 수 있어요.',403);const target=await db.prepare('SELECT id FROM rooms WHERE code=? AND teacher_hash=?').bind(clean(b.code,6).toUpperCase(),await hash(clean(b.teacherKey,64))).first();if(!target)fail('연결할 학급 코드와 교사 코드를 확인해 주세요.',403);const own=await membership(db,a.room.id),other=await membership(db,target.id);if(other&&other.campus!==(own?.campus||a.room.id))fail('이미 다른 학교에 연결된 학급이에요.',409);const campus=own?.campus||a.room.id;await db.batch([db.prepare('INSERT OR IGNORE INTO campuses(id) VALUES(?)').bind(campus),db.prepare('INSERT OR IGNORE INTO campus_rooms(room,campus,label) VALUES(?,?,?)').bind(a.room.id,campus,clean(b.homeLabel,20)||'우리 반 마을'),db.prepare('INSERT INTO campus_rooms(room,campus,label) VALUES(?,?,?) ON CONFLICT(room) DO UPDATE SET label=excluded.label WHERE campus=excluded.campus').bind(target.id,campus,clean(b.label,20)||'학급 '+clean(b.code,6))]);return board(db,a)}
if(path==='/api/campus/settings'&&method==='POST'){if(!a.teacher)fail('교사만 운영할 수 있어요.',403);const own=await membership(db,a.room.id);await db.batch([db.prepare('INSERT OR IGNORE INTO campuses(id) VALUES(?)').bind(own?.campus||a.room.id),db.prepare('INSERT OR IGNORE INTO campus_rooms(room,campus,label) VALUES(?,?,?)').bind(a.room.id,own?.campus||a.room.id,clean(b.label,20)||'우리 반 마을'),db.prepare('UPDATE campuses SET travel=?,library=? WHERE id=?').bind(b.travel?1:0,b.library?1:0,own?.campus||a.room.id),db.prepare('UPDATE campus_rooms SET label=? WHERE room=?').bind(clean(b.label,20)||own?.label||'우리 반 마을',a.room.id)]);return board(db,a)}
if(a.teacher)fail('학생으로 입장해 주세요.',403);
if(path==='/api/campus/passport'&&method==='POST'){if(a.room.paused)fail('수업이 일시정지되어 있어요.',423);if(b.answer!==1)fail('이웃의 물건과 기록을 존중하는 약속을 골라 주세요.');await db.prepare('INSERT OR IGNORE INTO passports(actor,issued) VALUES(?,?)').bind(a.player.id,Date.now()).run();return board(db,a)}
if(path==='/api/campus/visit'&&method==='POST'){const m=await membership(db,a.room.id);if(a.room.paused||!m?.travel)fail('선생님이 여행 시간을 열면 출발할 수 있어요.',423);if(!await db.prepare('SELECT actor FROM passports WHERE actor=?').bind(a.player.id).first())fail('여권을 먼저 발급해 주세요.',403);const target=await membership(db,clean(b.destination,64));if(!target||target.campus!==m.campus)fail('같은 학교의 연결된 마을만 방문할 수 있어요.',403);const residents=(await db.prepare('SELECT id,state FROM players WHERE room=? ORDER BY name').bind(target.room).all()).results.map(p=>{const s=JSON.parse(p.state);return {id:p.id,name:s.name,job:s.job,plots:s.farm.plots.length,planted:s.farm.plots.filter(x=>x.seeded).length}});await db.prepare('INSERT OR IGNORE INTO stamps(actor,destination,visited) VALUES(?,?,?)').bind(a.player.id,target.room,Date.now()).run();return {label:target.label,destination:target.room,residents}}
if(path!=='/api/campus/study'||method!=='POST')fail('경로를 찾을 수 없어요.',404);
const action=b.action,now=Date.now(),member=await membership(db,a.room.id),open=!a.room.paused&&(!member||member.library);
if(action==='start'){if(!open)fail('지금은 공부학교가 쉬는 시간이에요.',423);const goal=clean(b.goal,120),plan=Number(b.plan),seat=clean(b.seat,20),id=clean(b.id,80);if(!goal||![15,25,40].includes(plan)||!['창가','도서관','모닥불'].includes(seat)||!/^[a-zA-Z0-9_-]{8,80}$/.test(id))fail('오늘 목표와 집중 시간, 자리를 선택해 주세요.');const prior=await db.prepare('SELECT actor FROM study_sessions WHERE id=?').bind(id).first();if(prior){if(prior.actor!==a.player.id)fail('다시 시작해 주세요.',409);return board(db,a)}await db.prepare("INSERT INTO study_sessions(id,actor,room,goal,plan,seat,status,tick,created) VALUES(?,?,?,?,?,?,'active',?,?)").bind(id,a.player.id,a.room.id,goal,plan,seat,now,now).run();return board(db,a)}
for(let attempt=0;attempt<4;attempt++){const s=await db.prepare('SELECT * FROM study_sessions WHERE id=? AND actor=?').bind(clean(b.id,80),a.player.id).first();if(!s)fail('내 공부 기록을 다시 확인해 주세요.',404);if(['finished','cancelled'].includes(s.status))return board(db,a);const gap=Math.max(0,Math.floor((now-s.tick)/1000));const elapsed=Math.min(s.plan*60,s.elapsed+(s.status==='active'&&gap<=45&&open?gap:0));let status=s.status==='active'&&(!open||gap>45||elapsed>=s.plan*60)?'paused':s.status;
if(action==='pause')status='paused';else if(action==='resume'){if(!open)fail('지금은 공부학교가 쉬는 시간이에요.',423);if(elapsed>=s.plan*60)fail('집중 시간이 끝났어요. 마무리를 기록해 주세요.');status='active'}else if(!['heartbeat','finish','cancel'].includes(action))fail('활동을 다시 선택해 주세요.');
let result;if(action==='finish'){const reflection=clean(b.reflection,240),minutes=Number(b.minutes);if(!reflection||!Number.isInteger(minutes)||minutes<0||minutes>40||minutes*60>elapsed)fail('한 일을 적고 기록된 시간 이내로 실제 집중 시간을 선택해 주세요.');const day=new Date(now+9*3600000).toISOString().slice(0,10),earned=minutes>=1?Math.min(30,minutes+5):0;result=await db.prepare("UPDATE study_sessions SET status='finished',elapsed=?,reported=?,reflection=?,ended=?,tick=?,day=?,points=min(?,max(0,30-(SELECT coalesce(sum(points),0) FROM study_sessions WHERE actor=? AND day=?))),version=version+1 WHERE id=? AND actor=? AND version=? AND status IN ('active','paused')").bind(elapsed,minutes*60,reflection,now,now,day,earned,a.player.id,day,s.id,a.player.id,s.version).run()}else{result=await db.prepare('UPDATE study_sessions SET status=?,elapsed=?,tick=?,ended=?,version=version+1 WHERE id=? AND actor=? AND version=?').bind(action==='cancel'?'cancelled':status,elapsed,now,action==='cancel'?now:null,s.id,a.player.id,s.version).run()}if(result.meta?.changes)return board(db,a)}fail('다른 화면에서 기록이 바뀌었어요. 다시 확인해 주세요.',409)
}
