const fail=(message,status=400)=>{throw Object.assign(new Error(message),{status})};
const hash=async s=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s))),n=>n.toString(16).padStart(2,'0')).join('');
const clean=(v,max)=>String(v||'').trim().slice(0,max);
export const campusSchema=[
`CREATE TABLE IF NOT EXISTS campuses(id TEXT PRIMARY KEY,travel INTEGER NOT NULL DEFAULT 0,library INTEGER NOT NULL DEFAULT 1)`,
`CREATE TABLE IF NOT EXISTS campus_rooms(room TEXT PRIMARY KEY REFERENCES rooms(id),campus TEXT NOT NULL REFERENCES campuses(id),label TEXT NOT NULL)`,
`CREATE INDEX IF NOT EXISTS campus_members ON campus_rooms(campus)`,
`CREATE TRIGGER IF NOT EXISTS campus_limit BEFORE INSERT ON campus_rooms WHEN NOT EXISTS(SELECT 1 FROM campus_rooms WHERE room=NEW.room) AND (SELECT count(*) FROM campus_rooms WHERE campus=NEW.campus)>=4 BEGIN SELECT RAISE(ABORT,'CAMPUS_FULL'); END`,
`CREATE TRIGGER IF NOT EXISTS campus_ownership BEFORE INSERT ON campus_rooms WHEN EXISTS(SELECT 1 FROM campus_rooms WHERE room=NEW.room AND campus<>NEW.campus) BEGIN SELECT RAISE(ABORT,'CAMPUS_OWNERSHIP'); END`,
`CREATE TABLE IF NOT EXISTS passports(actor TEXT PRIMARY KEY,issued INTEGER NOT NULL)`,
`CREATE TABLE IF NOT EXISTS stamps(actor TEXT NOT NULL,destination TEXT NOT NULL,visited INTEGER NOT NULL,PRIMARY KEY(actor,destination))`,
`CREATE TABLE IF NOT EXISTS study_sessions(id TEXT PRIMARY KEY,actor TEXT NOT NULL,room TEXT NOT NULL,goal TEXT NOT NULL,plan INTEGER NOT NULL,seat TEXT NOT NULL,status TEXT NOT NULL,elapsed INTEGER NOT NULL DEFAULT 0,tick INTEGER NOT NULL,version INTEGER NOT NULL DEFAULT 0,created INTEGER NOT NULL,ended INTEGER,reflection TEXT NOT NULL DEFAULT '',reported INTEGER NOT NULL DEFAULT 0,points INTEGER NOT NULL DEFAULT 0,day TEXT)`,
`CREATE UNIQUE INDEX IF NOT EXISTS one_study_session ON study_sessions(actor) WHERE status IN ('active','paused')`,
`CREATE INDEX IF NOT EXISTS study_room ON study_sessions(room,status,tick)`,
`CREATE INDEX IF NOT EXISTS study_actor ON study_sessions(actor,created)`,
`CREATE INDEX IF NOT EXISTS study_daily ON study_sessions(actor,day,status)`,
`CREATE TABLE IF NOT EXISTS study_seats(room TEXT NOT NULL REFERENCES rooms(id),number INTEGER NOT NULL CHECK(number BETWEEN 1 AND 30),actor TEXT NOT NULL UNIQUE REFERENCES players(id),session TEXT NOT NULL UNIQUE,expires INTEGER NOT NULL,PRIMARY KEY(room,number))`,
`CREATE TRIGGER IF NOT EXISTS seat_permission BEFORE INSERT ON study_seats BEGIN
SELECT CASE WHEN NOT EXISTS(SELECT 1 FROM players p JOIN rooms home ON home.id=p.room JOIN rooms dest ON dest.id=NEW.room WHERE p.id=NEW.actor AND home.paused=0 AND dest.paused=0 AND coalesce((SELECT library FROM campuses WHERE id=(SELECT campus FROM campus_rooms WHERE room=p.room)),1)=1 AND (p.room=NEW.room OR EXISTS(SELECT 1 FROM campus_rooms h JOIN campus_rooms d ON d.campus=h.campus JOIN campuses c ON c.id=h.campus JOIN passports pp ON pp.actor=p.id WHERE h.room=p.room AND d.room=NEW.room AND c.travel=1))) THEN RAISE(ABORT,'SEAT_PERMISSION') END;
SELECT CASE WHEN EXISTS(SELECT 1 FROM study_sessions WHERE id=NEW.session AND (actor<>NEW.actor OR status NOT IN ('active','paused'))) THEN RAISE(ABORT,'SEAT_ENDED') END;
END`,
`CREATE TRIGGER IF NOT EXISTS study_seat_required BEFORE INSERT ON study_sessions WHEN NOT EXISTS(SELECT 1 FROM study_seats WHERE session=NEW.id AND actor=NEW.actor) BEGIN SELECT RAISE(ABORT,'SEAT_FULL'); END`,
`CREATE TRIGGER IF NOT EXISTS study_seat_lifecycle AFTER UPDATE ON study_sessions BEGIN
DELETE FROM study_seats WHERE session=NEW.id AND NEW.status IN ('finished','cancelled');
UPDATE study_seats SET expires=NEW.tick+900000 WHERE session=NEW.id AND expires>NEW.tick AND NEW.status IN ('active','paused');
END`
];
async function membership(db,room){return db.prepare('SELECT cr.*,c.travel,c.library FROM campus_rooms cr JOIN campuses c ON c.id=cr.campus WHERE cr.room=?').bind(room).first()}
export async function managedAuth(db,a,id){if(!id||id===a.room.id)return a;if(!a.teacher)fail('교사만 학급을 전환할 수 있어요.',403);const row=await db.prepare('SELECT r.* FROM rooms r JOIN campus_rooms x ON x.room=r.id JOIN campus_rooms y ON y.campus=x.campus WHERE y.room=? AND r.id=?').bind(a.room.id,id).first();if(!row)fail('관리 권한이 없는 학급이에요.',403);return {...a,room:row}}
async function board(db,a){
const actor=a.player?.id||'',now=Date.now();
// One database round trip for the shared room and personal dashboard.
const row=await db.prepare(`WITH membership AS (SELECT campus FROM campus_rooms WHERE room=?),reachable AS (SELECT room FROM campus_rooms WHERE campus=(SELECT campus FROM membership) UNION SELECT ?)
SELECT
(SELECT travel FROM campuses WHERE id=(SELECT campus FROM membership)) travel,
(SELECT library FROM campuses WHERE id=(SELECT campus FROM membership)) library,
(SELECT json_group_array(json_object('id',r.id,'code',r.code,'label',coalesce(c.label,'우리 반 마을'),'students',(SELECT count(*) FROM players WHERE room=r.id),'capacity',30,'paused',r.paused,'occupied',(SELECT count(*) FROM study_seats WHERE room=r.id AND expires>${now}))) FROM rooms r LEFT JOIN campus_rooms c ON c.room=r.id WHERE r.id IN (SELECT room FROM reachable)) rooms,
(SELECT json_group_array(json_object('id',id,'name',name,'room',room,'seat',seat,'status',status,'tick',tick)) FROM (SELECT p.id,json_extract(p.state,'$.name') name,s.room,s.seat,s.status,s.tick FROM study_sessions s JOIN players p ON p.id=s.actor WHERE s.room IN (SELECT room FROM reachable) AND s.status IN ('active','paused') AND s.tick>? ORDER BY s.created LIMIT 120)) peers,
(SELECT json_group_array(json_object('studyRoom',q.room,'number',q.number,'actor',q.actor,'name',json_extract(p.state,'$.name'),'home',p.room,'status',CASE WHEN st.status='active' AND st.tick>${now-45000} THEN '집중 중' ELSE '쉬는 중' END)) FROM study_seats q JOIN players p ON p.id=q.actor JOIN study_sessions st ON st.id=q.session WHERE q.room IN (SELECT room FROM reachable) AND q.expires>${now}) seats,
(SELECT issued FROM passports WHERE actor=?) passport,
(SELECT json_group_array(json_object('destination',destination,'visited',visited)) FROM stamps WHERE actor=?) stamps,
(SELECT json_object('id',id,'goal',goal,'plan',plan,'seat',seat,'status',status,'elapsed',elapsed,'tick',tick,'version',version,'created',created,'studyRoom',(SELECT room FROM study_seats WHERE session=study_sessions.id AND expires>${now}),'seatNumber',(SELECT number FROM study_seats WHERE session=study_sessions.id AND expires>${now})) FROM study_sessions WHERE actor=? AND status IN ('active','paused')) current,
(SELECT json_group_array(json_object('id',id,'goal',goal,'status',status,'created',created,'reported',reported,'reflection',reflection,'points',points)) FROM (SELECT * FROM study_sessions WHERE actor=? AND status IN ('finished','cancelled') ORDER BY created DESC LIMIT 12)) history,
(SELECT coalesce(sum(points),0) FROM study_sessions WHERE actor=?) points`).bind(a.room.id,a.room.id,now-90000,actor,actor,actor,actor,actor).first();
const rooms=JSON.parse(row.rooms).sort((a,b)=>a.label.localeCompare(b.label)),peers=JSON.parse(row.peers).map(p=>({...p,status:p.status==='active'&&now-p.tick<=45000?'집중 중':'쉬는 중'}));peers.forEach(p=>delete p.tick);
const shared={rooms,travel:!!row.travel,library:row.library===null?true:!!row.library,home:a.room.id,peers,seats:JSON.parse(row.seats)};
if(a.teacher){const records=(await db.prepare("SELECT s.*,p.name accountName,json_extract(p.state,'$.name') name FROM study_sessions s JOIN players p ON p.id=s.actor WHERE s.room=? ORDER BY s.created DESC LIMIT 240").bind(a.room.id).all()).results;return {...shared,records}}
return {...shared,actor:a.player.id,coins:JSON.parse(a.player.state).coins,name:JSON.parse(a.player.state).name,paused:!!a.room.paused,passport:row.passport||0,stamps:JSON.parse(row.stamps),current:row.current?JSON.parse(row.current):null,history:JSON.parse(row.history),points:row.points,serverTime:now}
}
export async function campusApi(db,a,path,b,method){if(path==='/api/campus'&&method==='GET')return board(db,a);
if(path==='/api/campus/link'&&method==='POST'){if(!a.teacher)fail('교사만 학급을 연결할 수 있어요.',403);const target=await db.prepare('SELECT id FROM rooms WHERE code=? AND teacher_hash=?').bind(clean(b.code,6).toUpperCase(),await hash(clean(b.teacherKey,64))).first();if(!target)fail('연결할 학급 코드와 교사 코드를 확인해 주세요.',403);const own=await membership(db,a.room.id),other=await membership(db,target.id);if(other&&other.campus!==(own?.campus||a.room.id))fail('이미 다른 학교에 연결된 학급이에요.',409);const campus=own?.campus||a.room.id;await db.batch([db.prepare('INSERT OR IGNORE INTO campuses(id) VALUES(?)').bind(campus),db.prepare('INSERT OR IGNORE INTO campus_rooms(room,campus,label) VALUES(?,?,?)').bind(a.room.id,campus,clean(b.homeLabel,20)||'우리 반 마을'),db.prepare('INSERT INTO campus_rooms(room,campus,label) VALUES(?,?,?) ON CONFLICT(room) DO UPDATE SET label=excluded.label WHERE campus=excluded.campus').bind(target.id,campus,clean(b.label,20)||'학급 '+clean(b.code,6))]);return board(db,a)}
if(path==='/api/campus/settings'&&method==='POST'){if(!a.teacher)fail('교사만 운영할 수 있어요.',403);const own=await membership(db,a.room.id);await db.batch([db.prepare('INSERT OR IGNORE INTO campuses(id) VALUES(?)').bind(own?.campus||a.room.id),db.prepare('INSERT OR IGNORE INTO campus_rooms(room,campus,label) VALUES(?,?,?)').bind(a.room.id,own?.campus||a.room.id,clean(b.label,20)||'우리 반 마을'),db.prepare('UPDATE campuses SET travel=?,library=? WHERE id=?').bind(b.travel?1:0,b.library?1:0,own?.campus||a.room.id),db.prepare('UPDATE campus_rooms SET label=? WHERE room=?').bind(clean(b.label,20)||own?.label||'우리 반 마을',a.room.id)]);return board(db,a)}
if(path==='/api/campus/seats/release'&&method==='POST'){if(!a.teacher)fail('교사만 자리를 반환할 수 있어요.',403);const n=Number(b.number);if(!Number.isInteger(n)||n<1||n>30)fail('좌석 번호를 확인해 주세요.');const q=await db.prepare('SELECT session FROM study_seats WHERE room=? AND number=?').bind(a.room.id,n).first();if(q)await db.batch([db.prepare("UPDATE study_sessions SET status='paused',tick=?,version=version+1 WHERE id=? AND status IN ('active','paused')").bind(Date.now(),q.session),db.prepare('DELETE FROM study_seats WHERE room=? AND number=? AND session=?').bind(a.room.id,n,q.session)]);return board(db,a)}
if(a.teacher)fail('학생으로 입장해 주세요.',403);
if(path==='/api/campus/passport'&&method==='POST'){if(a.room.paused)fail('수업이 일시정지되어 있어요.',423);if(b.answer!==1)fail('이웃의 물건과 기록을 존중하는 약속을 골라 주세요.');await db.prepare('INSERT OR IGNORE INTO passports(actor,issued) VALUES(?,?)').bind(a.player.id,Date.now()).run();return board(db,a)}
if(path==='/api/campus/visit'&&method==='POST'){const m=await membership(db,a.room.id);if(a.room.paused||!m?.travel)fail('선생님이 여행 시간을 열면 출발할 수 있어요.',423);if(!await db.prepare('SELECT actor FROM passports WHERE actor=?').bind(a.player.id).first())fail('여권을 먼저 발급해 주세요.',403);const target=await membership(db,clean(b.destination,64));if(!target||target.campus!==m.campus)fail('같은 학교의 연결된 마을만 방문할 수 있어요.',403);const residents=(await db.prepare('SELECT id,state FROM players WHERE room=? ORDER BY name').bind(target.room).all()).results.map(p=>{const s=JSON.parse(p.state);return {id:p.id,name:s.name,job:s.job,plots:s.farm.plots.length,planted:s.farm.plots.filter(x=>x.seeded).length}});await db.prepare('INSERT OR IGNORE INTO stamps(actor,destination,visited) VALUES(?,?,?)').bind(a.player.id,target.room,Date.now()).run();return {label:target.label,destination:target.room,residents}}
if(path!=='/api/campus/study'||method!=='POST')fail('경로를 찾을 수 없어요.',404);
const action=b.action,now=Date.now(),member=await membership(db,a.room.id),open=!a.room.paused&&(!member||member.library);
if(action==='start'){if(!open)fail('지금은 공부학교가 쉬는 시간이에요.',423);const goal=clean(b.goal,120),plan=Number(b.plan),seat=clean(b.seat,20),id=clean(b.id,80);if(!goal||![15,25,40].includes(plan)||!['창가','도서관','모닥불'].includes(seat)||!/^[a-zA-Z0-9_-]{8,80}$/.test(id))fail('오늘 목표와 집중 시간, 자리를 선택해 주세요.');const prior=await db.prepare('SELECT actor FROM study_sessions WHERE id=?').bind(id).first();if(prior){if(prior.actor!==a.player.id)fail('다시 시작해 주세요.',409);return board(db,a)}const reservations=await reserveSeat(db,a,b,id,now);await db.batch([...reservations,db.prepare("INSERT INTO study_sessions(id,actor,room,goal,plan,seat,status,tick,created) VALUES(?,?,?,?,?,(SELECT CASE WHEN number<=12 THEN '도서관' WHEN number<=24 THEN '창가' ELSE '모닥불' END FROM study_seats WHERE session=?),'active',?,?)").bind(id,a.player.id,a.room.id,goal,plan,id,now,now)]);if(!await db.prepare('SELECT id FROM study_sessions WHERE id=?').bind(id).first())fail('이 공부방은 만석이에요. 다른 자리나 공부방을 골라 주세요.',409);return board(db,a)}
for(let attempt=0;attempt<4;attempt++){const s=await db.prepare('SELECT * FROM study_sessions WHERE id=? AND actor=?').bind(clean(b.id,80),a.player.id).first();if(!s)fail('내 공부 기록을 다시 확인해 주세요.',404);if(['finished','cancelled'].includes(s.status))return board(db,a);const lease=await db.prepare('SELECT q.*,r.paused destinationPaused FROM study_seats q JOIN rooms r ON r.id=q.room WHERE q.session=? AND q.expires>?').bind(s.id,now).first();if(action==='claim'){const reservations=await reserveSeat(db,a,b,s.id,now);await db.batch([...reservations,db.prepare("UPDATE study_sessions SET status='paused',seat=(SELECT CASE WHEN number<=12 THEN '도서관' WHEN number<=24 THEN '창가' ELSE '모닥불' END FROM study_seats WHERE session=?),tick=?,version=version+1 WHERE id=? AND actor=? AND status IN ('active','paused')").bind(s.id,now,s.id,a.player.id)]);return board(db,a)}const canStudy=open&&!!lease&&!lease.destinationPaused&&(lease.room===a.room.id||member?.travel);const gap=Math.max(0,Math.floor((now-s.tick)/1000));const elapsed=Math.min(s.plan*60,s.elapsed+(s.status==='active'&&gap<=45&&canStudy?gap:0));let status=s.status==='active'&&(!canStudy||gap>45||elapsed>=s.plan*60)?'paused':s.status;
if(action==='pause')status='paused';else if(action==='resume'){if(!lease)fail('자리가 반환됐어요. 빈자리를 다시 선택해 주세요.',409);if(!canStudy)fail('지금은 공부학교가 쉬는 시간이에요.',423);if(elapsed>=s.plan*60)fail('집중 시간이 끝났어요. 마무리를 기록해 주세요.');status='active'}else if(!['heartbeat','finish','cancel'].includes(action))fail('활동을 다시 선택해 주세요.');
let result;if(action==='finish'){const reflection=clean(b.reflection,240),minutes=Number(b.minutes);if(!reflection||!Number.isInteger(minutes)||minutes<0||minutes>40||minutes*60>elapsed)fail('한 일을 적고 기록된 시간 이내로 실제 집중 시간을 선택해 주세요.');const day=new Date(now+9*3600000).toISOString().slice(0,10),earned=minutes>=1?Math.min(30,minutes+5):0;result=await db.prepare("UPDATE study_sessions SET status='finished',elapsed=?,reported=?,reflection=?,ended=?,tick=?,day=?,points=min(?,max(0,30-(SELECT coalesce(sum(points),0) FROM study_sessions WHERE actor=? AND day=?))),version=version+1 WHERE id=? AND actor=? AND version=? AND status IN ('active','paused')").bind(elapsed,minutes*60,reflection,now,now,day,earned,a.player.id,day,s.id,a.player.id,s.version).run()}else{result=await db.prepare('UPDATE study_sessions SET status=?,elapsed=?,tick=?,ended=?,version=version+1 WHERE id=? AND actor=? AND version=?').bind(action==='cancel'?'cancelled':status,elapsed,now,action==='cancel'?now:null,s.id,a.player.id,s.version).run()}if(result.meta?.changes)return board(db,a)}fail('다른 화면에서 기록이 바뀌었어요. 다시 확인해 주세요.',409)
}

async function reserveSeat(db,a,b,id,now){const room=clean(b.studyRoom,64)||a.room.id,number=b.seatNumber===undefined?null:Number(b.seatNumber);if(number!==null&&(!Number.isInteger(number)||number<1||number>30))fail('1번부터 30번 사이의 빈자리를 선택해 주세요.');if(b.action==='claim'&&number===null)fail('반환된 자리는 빈자리를 직접 골라 다시 앉아 주세요.');if(room!==a.room.id){const own=await membership(db,a.room.id),dest=await membership(db,room);if(!own||!dest||own.campus!==dest.campus||!own.travel)fail('선생님이 여행을 열면 다른 반 공부방에 갈 수 있어요.',403);if(!await db.prepare('SELECT actor FROM passports WHERE actor=?').bind(a.player.id).first())fail('다른 반 공부방은 여권 발급 후 방문할 수 있어요.',403)}
const statements=[db.prepare('DELETE FROM study_seats WHERE expires<=? AND (room=? OR actor=?)').bind(now,room,a.player.id)];if(b.action==='claim')statements.push(db.prepare('DELETE FROM study_seats WHERE actor=?').bind(a.player.id));
if(number!==null)statements.push(db.prepare('INSERT INTO study_seats(room,number,actor,session,expires) VALUES(?,?,?,?,?)').bind(room,number,a.player.id,id,now+900000));else{const lo=b.seat==='창가'?13:b.seat==='모닥불'?25:1,hi=b.seat==='창가'?24:b.seat==='모닥불'?30:12;statements.push(db.prepare("WITH RECURSIVE slots(n) AS (SELECT 1 UNION ALL SELECT n+1 FROM slots WHERE n<30) INSERT INTO study_seats(room,number,actor,session,expires) SELECT ?,n,?,?,? FROM slots WHERE NOT EXISTS(SELECT 1 FROM study_seats WHERE room=? AND number=n) ORDER BY CASE WHEN n BETWEEN ? AND ? THEN 0 ELSE 1 END,n LIMIT 1").bind(room,a.player.id,id,now+900000,room,lo,hi))}return statements}
