import {careerSnapshot} from './career-data.mjs';
import {seasonSchema,seasonAction} from './garden-seasons.mjs';
import {crops,questions,garden,cropStock,changeCrop,cropPrice,farmProgress} from './growth-data.mjs';
const fail=(s,status=400)=>{throw Object.assign(Error(s),{status})};
export const growthSchema=[
`CREATE TABLE IF NOT EXISTS growth_policy(room TEXT PRIMARY KEY,mode TEXT NOT NULL DEFAULT 'calendar')`,
`CREATE TABLE IF NOT EXISTS growth_schooldays(room TEXT NOT NULL,day TEXT NOT NULL,PRIMARY KEY(room,day))`,
`CREATE TABLE IF NOT EXISTS growth_badges(actor TEXT NOT NULL,id TEXT NOT NULL,earned INTEGER NOT NULL,reason TEXT NOT NULL,PRIMARY KEY(actor,id))`,
`CREATE TABLE IF NOT EXISTS garden_totals(room TEXT NOT NULL,crop INTEGER NOT NULL,qty INTEGER NOT NULL DEFAULT 0,PRIMARY KEY(room,crop))`,
`CREATE TABLE IF NOT EXISTS garden_roles(room TEXT NOT NULL,step INTEGER NOT NULL,actor TEXT NOT NULL,created INTEGER NOT NULL,PRIMARY KEY(room,step))`,
`CREATE TRIGGER IF NOT EXISTS garden_role_guard BEFORE INSERT ON commands WHEN NEW.kind='garden_role' BEGIN
SELECT CASE WHEN (SELECT count(*) FROM garden_totals WHERE room=NEW.room AND qty>=30)<5 OR (SELECT count(*) FROM garden_roles WHERE room=NEW.room)<>NEW.item THEN RAISE(ABORT,'GARDEN_CHANGED') END;
END`,
`CREATE TRIGGER IF NOT EXISTS garden_apply AFTER INSERT ON commands BEGIN
INSERT INTO garden_totals(room,crop,qty) SELECT NEW.room,NEW.item,NEW.qty WHERE NEW.kind='crop_donate' ON CONFLICT(room,crop) DO UPDATE SET qty=qty+excluded.qty;
INSERT INTO garden_roles(room,step,actor,created) SELECT NEW.room,NEW.item,NEW.actor,NEW.created WHERE NEW.kind='garden_role';
END`,...seasonSchema
];
const stages=[{title:'포장 담당',question:'여러 재료를 도시락용으로 보낼 때 먼저 할 일은?',answers:['식재료와 알레르기·보관 정보를 확인한다','내용물 표시를 생략한다','상한 재료도 섞는다']},{title:'운송 담당',question:'폭우로 원래 배송 도로가 통제되었어요. 어떻게 할까요?',answers:['통제 정보를 확인하고 안전한 우회·보관 계획을 세운다','통제된 도로를 그냥 지난다','냉장 재료를 밖에 오래 둔다']},{title:'조리·영양 담당',question:'함께 먹을 도시락을 준비할 때 중요한 것은?',answers:['손과 도구를 씻고 알레르기와 충분한 가열을 확인한다','알레르기 정보는 무시한다','남은 음식은 아무 곳에 보관한다']}];
export function prepareGrowth(input,s,room){const g=garden(s),i=input.crop,qty=input.qty;if(!Number.isInteger(i)||i<0||i>4)fail('작물을 확인해 주세요.');if(!Number.isInteger(qty)||qty<1||qty>50)fail('1~50개 사이 수량을 선택해 주세요.');if(cropStock(s,i)<qty)fail('이 작물의 재고가 부족해요.');changeCrop(s,i,-qty);if(input.action==='crop_donate'){g.given[i]+=qty;s.history.unshift(crops[i].name+' '+qty+'개를 공동 도시락에 기부했어요.')}else{s.coins+=qty*cropPrice(crops[i],room);s.history.unshift(crops[i].name+' '+qty+'개를 매입소에 판매했어요.')}s.history=s.history.slice(0,20);return {item:i,qty}}
export function prepareGardenRole(b,s){if(!Number.isInteger(b.step)||b.step<0||b.step>2||b.answer!==0)fail('안전하고 서로를 배려하는 방법을 골라 주세요.');s.gardenHelp=true;return {item:b.step,qty:0}}
export function streaks(days,mode,schooldays=[]){const eligible=days.filter(d=>d.seconds>=600).map(d=>d.day).sort();let best=0,run=0,last=null;const schedule=new Map(schooldays.map((d,i)=>[d,i]));for(const d of eligible){const index=mode==='school'?schedule.get(d):Math.floor(Date.parse(d+'T00:00:00Z')/86400000);if(index===undefined)continue;run=last!==null&&index===last+1?run+1:1;best=Math.max(best,run);last=index}return best}
export async function growthApi(db,a,path,b,method){
if(['/api/growth/season-settings','/api/growth/next-season'].includes(path)&&method==='POST')await seasonAction(db,a,path,b);
if(path==='/api/growth/policy'&&method==='POST'){if(!a.teacher)fail('교사만 설정할 수 있어요.',403);if(!['calendar','school'].includes(b.mode))fail('출석 기준을 선택해 주세요.');await db.prepare('INSERT INTO growth_policy(room,mode) VALUES(?,?) ON CONFLICT(room) DO UPDATE SET mode=excluded.mode').bind(a.room.id,b.mode).run()}
if(path==='/api/growth/schoolday'&&method==='POST'){if(!a.teacher)fail('교사만 수업일을 기록할 수 있어요.',403);const day=new Date(Date.now()+32400000).toISOString().slice(0,10);await db.prepare('INSERT OR IGNORE INTO growth_schooldays(room,day) VALUES(?,?)').bind(a.room.id,day).run()}
if(path==='/api/growth/award'&&method==='POST'){if(!a.teacher)fail('교사만 도장을 찍을 수 있어요.',403);const student=await db.prepare('SELECT id FROM players WHERE id=? AND room=?').bind(String(b.actor),a.room.id).first();if(!student)fail('이 학급의 학생을 선택해 주세요.');const reason=String(b.reason||'').trim();if(reason.length<2||reason.length>120)fail('도장을 주는 이유를 2~120자로 적어 주세요.');await db.prepare("INSERT OR IGNORE INTO growth_badges(actor,id,earned,reason) VALUES(?,'kind-neighbor',?,?)").bind(student.id,Date.now(),reason).run()}
if(!['/api/growth','/api/growth/policy','/api/growth/schoolday','/api/growth/award','/api/growth/season-settings','/api/growth/next-season'].includes(path))fail('경로를 확인해 주세요.',404);
const actor=a.player?.id||'';
const seasonRow=await db.prepare("SELECT coalesce((SELECT number FROM garden_seasons WHERE room=?),1) number,coalesce((SELECT automatic FROM garden_seasons WHERE room=?),0) automatic,(SELECT json_group_array(json_object('season',season,'completed',completed,'participants',participants)) FROM (SELECT * FROM garden_archive WHERE room=? ORDER BY season DESC LIMIT 6)) history,(SELECT count(*) FROM garden_participants WHERE room=? AND season=coalesce((SELECT number FROM garden_seasons WHERE room=?),1) AND actor=?) participating").bind(a.room.id,a.room.id,a.room.id,a.room.id,a.room.id,actor).first();
const row=await db.prepare(`SELECT
coalesce((SELECT mode FROM growth_policy WHERE room=?),'calendar') mode,
(SELECT json_group_array(day) FROM (SELECT day FROM growth_schooldays WHERE room=? ORDER BY day)) schooldays,
(SELECT json_group_array(json_object('crop',crop,'qty',qty)) FROM garden_totals WHERE room=?) totals,
(SELECT json_group_array(json_object('step',step,'actor',actor,'created',created)) FROM garden_roles WHERE room=?) roles,
(SELECT json_group_array(json_object('day',day,'seconds',seconds)) FROM (SELECT day,sum(reported) seconds FROM study_sessions WHERE actor=? AND status='finished' GROUP BY day)) days,
(SELECT json_group_array(json_object('id',id,'earned',earned,'reason',reason)) FROM growth_badges WHERE actor=?) badges`).bind(a.room.id,a.room.id,a.room.id,a.room.id,actor,actor).first();
const days=JSON.parse(row.days||'[]'),roles=JSON.parse(row.roles||'[]'),schooldays=JSON.parse(row.schooldays||'[]'),badges=JSON.parse(row.badges||'[]');const totalMinutes=Math.floor(days.reduce((n,d)=>n+d.seconds,0)/60),longest=streaks(days,row.mode,schooldays);const s=a.player?JSON.parse(a.player.state):null,g=s?garden(s):null;
const definitions=[{id:'career-explorer',title:'교과 탐험가',value:s?.career?.solved?.length||0,target:6,reason:'교과·학과 탐험 6문제 해결'},{id:'learning-plan',title:'나의 배움 설계',value:Object.keys(s?.career?.cart||{}).length,target:3,reason:'관심 과목 3개에 선택 이유 기록'},...[7,14].map(n=>({id:'streak-'+n,title:'도서관 '+n+'일 연속',value:longest,target:n,reason:'하루 10분 이상 공부하고 마무리 기록 · '+(row.mode==='school'?'교사 지정 수업일':'매일')+' 기준'})),...[60,180,600].map(n=>({id:'focus-'+n,title:'누적 집중 '+n+'분',value:totalMinutes,target:n,reason:'마무리한 공부의 기록 시간 합계'})),...[10,30,50].map(n=>({id:'quiz-'+n,title:'퀴즈왕 '+n+'문제',value:s?.quizSolved?.length||0,target:n,reason:'서로 다른 직업 문제 정답'})),...[5,20,50].map(n=>({id:'giving-'+n,title:'나눔 농부 '+n+'개',value:g?.given.reduce((a,b)=>a+b,0)||0,target:n,reason:'게임 속 공동 도시락에 작물 기부'})),...[3,5].map(n=>({id:'variety-'+n,title:'다양한 농장 '+n+'종',value:g?.harvested.filter(n=>n>0).length||0,target:n,reason:'서로 다른 작물 직접 수확'})),{id:'first-harvest',title:'첫 수확',value:s?.farm.picked||0,target:1,reason:'내 밭에서 첫 작물 수확'},{id:'shared-lunch',title:'첫 공동 도시락',value:roles.length===3&&seasonRow.participating>0?1:0,target:1,reason:'재료 기부 또는 역할을 맡아 공동 도시락 완성'},{id:'kind-neighbor',title:'고마운 이웃',value:0,target:1,reason:'선생님이 관찰한 배려와 협력'}];
if(s){const earned=definitions.filter(d=>d.value>=d.target&&!badges.some(b=>b.id===d.id));if(earned.length){const now=Date.now();await db.batch(earned.map(d=>db.prepare('INSERT OR IGNORE INTO growth_badges(actor,id,earned,reason) VALUES(?,?,?,?)').bind(actor,d.id,now,d.reason)));badges.push(...earned.map(d=>({id:d.id,earned:now,reason:d.reason})))}}
const next=questions.find(q=>!s?.quizSolved?.includes(q.id));return {career:careerSnapshot(s),progress:s?farmProgress(s):null,crops:crops.map(c=>({...c,price:cropPrice(c,a.room)})),mode:row.mode,schooldays,project:{season:seasonRow.number,automatic:!!seasonRow.automatic,history:JSON.parse(seasonRow.history||'[]'),totals:JSON.parse(row.totals||'[]'),roles,goal:30,stages},badges:definitions.map(d=>({...d,...badges.find(b=>b.id===d.id)})),quiz:next?{id:next.id,prompt:next.prompt,answers:next.answers}:null,stock:s?crops.map(c=>cropStock(s,c.id)):[],teacher:!!a.teacher,home:a.room.id,paused:!!a.room.paused};
}
